### PR TITLE
native fsNotifier: try to use a rule-based filename as alternative for ex. aarch64

### PR DESCRIPTION
**Pull request by jglathe**
These patches add a platform-specific fsnotifier for linux-aarch64. It also extends NativeFileWatcherImpl.getExecutable() to generate a platform-specific filename to look for if the hardcoded choices are not met. 
Follow-up on #1126 , please see for more details on the whereabouts.
Tried and tested on a Jetson nano, with IDEA and PyCharm 191.7479.

### CODE REVIEW

**Comment by franckrasolo** [comment]
FYI https://www.linuxondex.com is another use case where this would help.

**Comment by trespasserw** [comment]
Sorry for the late reply.

At the moment, JB does not want to support other architectures besides x86/x86-64. Starting from the next 2019.3 build, IDEs will provide a user with instructions on building and installing the `fsnotifier` binary on their system.

**Comment by jglathe** [comment]
If this means that the local-arch fsnotifier will be loaded, good. Otherwise, how does this work?

**Comment by trespasserw** [comment]
With some help from a user, yes. Here are the instructions: https://confluence.jetbrains.com/display/IDEADEV/Compiling+File+Watcher.

**Comment by jglathe** [comment]
Great, thanks!

**Comment by jpalus** [comment]
Note that IJ 2019.3 with native fsnotifier compiled still logs exception in other part:
```
2019-11-28 14:12:24,641 [  17880]   WARN - openapi.util.io.FileSystemUtil - Failed to load filesystem access layer: Linux, 13.0.1 
java.lang.IllegalStateException: Unsupported OS/arch: Linux/aarch64
	at com.intellij.openapi.util.io.FileSystemUtil$JnaUnixMediatorImpl.<init>(FileSystemUtil.java:290)
	at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:55)
	at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:46)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.getAttributes(LocalFileSystemBase.java:723)
```

**Comment by trespasserw** [comment]
^ Just a warning; one can get rid of it by adding `idea.io.use.nio2 = true` to *Help | Edit Custom Properties*.

**Comment by jglathe** [comment]
That's great, should be added to https://confluence.jetbrains.com/display/IDEADEV/Compiling+File+Watcher. No idea if it increases the speed, when I understood the code correctly nio2 is already the fallback when no libc stat is available.

**Comment by trespasserw** [comment]
No, it shouldn't - first, it is not related in any way to `fsnotifier`; second, we're going to use NIO2 by default (probably in the next version).

**Pull request closed without merging**
