### PR TITLE
IDEA-146898 DoubleNegationInspection only for booleans

### PR DESCRIPTION
**Pull request by vladmm**
The DoubleNegationInspection should only register error for booleans and conditional statements.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by vladmm** [comment]
Hi @klikh ,
Thank you for the reminder. I sent it.

**Comment by klikh** [comment]
Received. Thanks.

**Comment by ignatov** [comment]
@vladmm, please rebase the PR, cc @dovchinnikov.

**Comment by dovchinnikov** [comment]
The code is okay, but there are other boolean contexts such as `assert` statement or ternary expression. Support for all of them is needed before this could be merged.

Please reopen the request once it ready.

**Pull request closed without merging**
