### PR TITLE
Fix for IDEA-180133: allow hg4idea to set hg executable per-project

### PR DESCRIPTION
**Pull request by mkillianey**
Details at https://youtrack.jetbrains.com/issue/IDEA-180133

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by mkillianey** [comment]
Done!

**Comment by mkillianey** [comment]
@klikh - Just a gentle reminder that this is still out here.  If there's anything else I should do (perhaps pull-request to the 173 branch instead of 172?), just let me know.

**Comment by klikh** [comment]
@mkillianey Thanks for your contribution. My colleague [answered](https://github.com/JetBrains/intellij-community/pull/641#issuecomment-339029021) in the related issue that we're going to implement this a bit differently to overcome the usability issue. We plan to make the fix soon, both for Git and Hg.

**Pull request closed without merging**
