### PR TITLE
Fix IDEA-141538: XML validator does not use a relative path to the XSD

### PR DESCRIPTION
**Pull request by rosti-il**
Fixes https://youtrack.jetbrains.com/issue/IDEA-141538
and probably https://youtrack.jetbrains.com/issue/IDEA-146915

### CODE REVIEW

**Comment by rosti-il** [comment]
The original code before this fix had registered two instances of `ResourceResolver` three times: 1) `myXmlResourceResolver`; 2) `DefaultHandler` (that also implements `ResourceResolver`); 3) `myXmlResourceResolver` again by a dirty trick with `startDocument()`. My fix not only fixes the bug but also makes the code clean and only one instance `ResourceResolver` is created and register in the `myParser` only once.

**Comment by rosti-il** [comment]
I accidentally closed this PR in posting my the previous comment. Reopened it now.

**Comment by rosti-il** [comment]
When you debug this code you probably wants to debug the Xerces code as well. To do so with a debugger you need to make and use your own build of Xerces with `debug` property turned `on` because the official release contains JAR without any debug information including the line number information.

For discussion about why they did so go to http://markmail.org/thread/qkbaup5dzjrx5ffj

**Comment by dmitry-avdeev** [comment]
Thanks @rosti-il, unfortunately this cannot be accepted as-is because it breaks some tests from XmlHighlightingTest (mainly XInclude support). Based on your main idea of providing systemId to the original InputSource I've mastered a minimal patch to be backported to 2018.3 bugfix updates. Thanks again for great job and feel free to submit corrected patch with other improvements, we'll take it into our master.

**Comment by rosti-il** [comment]
@dmitry-avdeev ok. Could you advise me what is the right way to run all tests before commit? It's not clearly explained in the `README.md`.

**Comment by dmitry-avdeev** [comment]
Running all tests from intellij.xml.tests would be enough.

**Comment by rosti-il** [comment]
@dmitry-avdeev please take a look at my new PR that continues this one:
https://github.com/JetBrains/intellij-community/pull/1021

**Pull request closed without merging**
