### PR TITLE
Custom postfix templates

### PR DESCRIPTION
**Pull request by xylo**
This pull request implements a very simple version of the custom postfix templates requested in https://youtrack.jetbrains.com/issue/IDEA-122443.

It allows to define the postfix templates in `$HOME/.ideaPostfixTemplates` (one template per line).
The format of each line is:
```
EXPRESSION_TYPE → TEMPLATE_NAME → DESCRIPTION → TEMPLATE
```
* EXPRESSION_TYPE denotes the type of the expression the template may be applied to
  * can be a normal Java class (e.g. java.lang.String) or one of these: ARRAY, BOOLEAN, ITERABLE_OR_ARRAY, NON_VOID, NOT_PRIMITIVE, NUMBER
* TEMPLATE_NAME denotes the template name
* DESCRIPTION is a short description of the template that is shown in the code completion popup
* TEMPLATE is the template code used to replace the expression
  * $expr$ is replaced by the expression the template is applied to
  * $END$ denotes the end position of the cursor

Example:
```
java.lang.String  →  toInt   →  Integer.parse(string)    →  Integer.parse($expr$)$END$
ARRAY             →  toList  →  Arrays.asList(array)     →  Arrays.asList($expr$)$END$
java.util.List    →  toSet   →  new HashSet<>(list)      →  new HashSet<>($expr$)$END$
java.lang.String  →  r       →  Pattern.compile(string)  →  Pattern.compile($expr$)$END$

```

### CODE REVIEW

**Comment by xylo** [comment]
I created a repository for collecting postfix templates for different user groups: https://github.com/xylo/intellij-postfix-templates

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by xylo** [comment]
@kirillk 
I tried to submit the CLA form with my data, but I got the following error: "Something is wrong. Please, try again later or reach out to us via contribute@jetbrains.com"

@anstarovoyt 
Good answer!  I think I would suggest the same in your situation. :)
So I have to options: Make the adaptations UI friendly or export it into a plugin.  Since both solutions will take some time, I would prefer to implement the UI stuff and extend this pull request in the next weeks.  Before I start I will post a concrete proposal here so that we can discuss it.

By the way thanks for the your tips regarding the storing path.  I was already searching for something like this, but couldn't find it so fast.

**Comment by klikh** [comment]
@xylo I've just tried, and it worked for me. At what stage did it fail? Right after you filled the web form, or after you've signed the online pdf document? Could you please try again and send me (kirill.likhodedov@jetbrains.com) a screenshot of the error if it still fails? We'd like to understand the issue and fix it.

**Comment by xylo** [comment]
I'm closing this pull request since it was only a hack and I'm currently working on a more advanced plugin that provides the same functionality: https://github.com/xylo/intellij-postfix-templates

**Pull request closed without merging**
