### PR TITLE
add table as a manifest token type

### PR DESCRIPTION
**Pull request by Seiphon**
pr related to https://youtrack.jetbrains.com/issue/IDEA-229986

### CODE REVIEW

**Comment by ybedrov** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by Seiphon** [comment]
> Hello! Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

Have submitted the contributor license agreement.

**Comment by trespasserw** [comment]
Sorry for the late reply :(

Unfortunately, the suggested fix is correct for .bnd files (or for .MF files processed by BndLib), but rules for non-OSGi .MF files are [much more strict](https://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Notes_on_Manifest_and_Signature_Files).

**Comment by Seiphon** [comment]
OK, that make sence, thanks for your explaination.

**Pull request closed without merging**
