### PR TITLE
Always check PATH in Git detector

### PR DESCRIPTION
**Pull request by fkorotkov**
With the change the detector works fine with my custom git location.

### CODE REVIEW

**Comment by fkorotkov** [comment]
FYI @klikh. Would be nice to have it cherry-picked in 15.

**Comment by klikh** [comment]
LGTM. Have you checked `GitExecutableDetectorWindowsTest`?

**Comment by fkorotkov** [comment]
I assumed it's only for windows and I have only Mac.

**Comment by klikh** [comment]
I've checked it myself, it fails because the code is referring to the PathEnvironmentVariableUtil which is no more overridden in tests. I'll prepare the fix and merge the updated change soon.

**Comment by fkorotkov** [comment]
Thanks a ton!

**Comment by klikh** [comment]
Just found another problem: there are two valid executable formats for Git on Windows: git.cmd and git.exe. In this PR only git.exe is considered. Moreover, it is not enough to, for instance, check the PATH for git.exe and then check it for git.cmd, since if both are available in the PATH, the first one should be preferred.

Currently working on it. Luckily, I wrote this test a while ago, otherwise wouldn't capture this.

**Comment by iasemenov** [comment]
I've ported this PR to current master.
See commit 06e4dec6000d3fb7193caa6c597e7107005b0fef
Thank you, @fkorotkov

**Pull request closed without merging**
