### PR TITLE
Open/Close Task Dialogs improvement.

### PR DESCRIPTION
**Pull request by DmitryKachurin**
Add possibility to extend open and close task dialogs.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by DmitryKachurin** [comment]
I have done it.

**Comment by klikh** [comment]
Received, thank you.

**Comment by dmitry-avdeev** [comment]
What is it for? What is your use case?

**Comment by DmitryKachurin** [comment]
It gives ability to add custom options in open/close task dialogs.

The developer will override methods getOpenTaskControlPanelProvider and getCloseTaskControlPanelProvider to extend open and close task dialogs (add some unique functional). Add assignee to task, Ad task to folder or change status of task.

Example:
picture

**Comment by DmitryKachurin** [comment]
Did this information enough or need more details?

**Comment by dmitry-avdeev** [comment]
Hi, AFAIK we already have "Update issue state" feature.

**Comment by DmitryKachurin** [comment]
Hi, current functionality is not enought to manage statuses in Wrike.

**Comment by dmitry-avdeev** [comment]
It seems we need more general approach to meet requests like this one: https://github.com/OpherV/gitflow4idea/issues/104.

**Comment by DmitryKachurin** [comment]
Do you mean that I need to create extension point for plugin 'Tasks' in this case to satisfy to both problems?

**Comment by dmitry-avdeev** [comment]
Hi, I have created such an API:
https://github.com/JetBrains/intellij-community/commit/f7a02a6ee8e6228bebfc7699c30ec76a27a2dd55.
Please review and check if it satisfies your needs.

2016-02-26 13:31 GMT+03:00 DmitryKachurin <notifications@github.com>:

**Comment by DmitryKachurin** [comment]
I have checked and it satisfies my needs. Thanks!

**Pull request closed without merging**
