### PR TITLE
Fix IDEA-201331: Respect the annotations processors order

### PR DESCRIPTION
**Pull request by Im-dex**
Fix for https://youtrack.jetbrains.com/issue/IDEA-201331

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by graemerocher** [comment]
@Im-dex nice!

**Comment by nskvortsov** [comment]
Thank you!
merged manually

**Comment by sneakythr0ws** [comment]
IU-191.7479.1 is affected.
Project compiles but doesn't respect gradle definition order of annotation processors.
Request to controller fails with "Internal Server Error: Error instantiating bean of type [example.micronaut.Application$ConferenceController]: example.micronaut.Application$ConferenceController: method <init>()V not found"
https://github.com/sneakythr0ws/MicronautAndLombok

**Pull request closed without merging**
