### PR TITLE
Refactored external system services to reduce amount or write actions

### PR DESCRIPTION
**Pull request by fkorotkov**
Description:

It appeared that most of the default services were executing a lot of write actions to commit models. Also services were committing models in write actions even if there were no changes to these models.

This refactoring tries to collect all the modifiable models and perform all commits in just one write action. Also before a commit all models are checked for changes. It affects performance of an incremental refresh drastically for huge projects.

Testing:

All 5 tests for external build system are passing. :-) Also manually tested on a project with 2227 modules. Incremental refresh on dependency/library changes was super fast!

It would be very nice if you guys can run the change on CI.

### CODE REVIEW

**Comment by chashnikov** [comment]
Merged to master, thank you for the contribution!

I also did some fixes myself. Firstly, I changed order of statements in 'LibraryTableBase.LibraryModel#commit', otherwise 'isChanged' will return 'false' during 'commit' so no events will be fired. Secondly, I introduced method 'ExceptionUtil.rethrowAllAsUnchecked' and used it instead of 'rethrowUnchecked' to ensure that if the code will be changed in the future and start producing checked exceptions they won't be silently ignored.

**Comment by fkorotkov** [comment]
Awesome! Спасибо, Коля!

dancing

**Comment by fkorotkov** [comment]
Does 142.4675.3 include the fix?

**Comment by fkorotkov** [comment]
Nope. It's included in 142.4712.

**Comment by fkorotkov** [comment]
Built IntelliJ from sources. Much faster! But I think there is a room for even more improvements. Will do another round of profiling after my upcoming PTO.

**Pull request closed without merging**
