### PR TITLE
FIR/UAST: resolve @Retention value

### PR DESCRIPTION
**Pull request by jsjeon**
While removing usage of UAST implementations in [Metalava](https://cs.android.com/android/_/android/platform/tools/metalava/+/3b3e2e8dd291ea84c22a4aee6e3718634a341ee3), learned how they use UAST to retrieve `@Retention` value:
```kt
@Retention(AnnotationRetention.SOURCE)
internal annotation class DialogFlags

class Inner {
  fun setInner(@DialogFlags flags: Int) {}
}
```
Here, Metalava wants to determine if a class/member/type/parameter is annotated with an annotation class, which has `SOURCE`-level `@Retention`. To reach the enum entry (`SOURCE`) as an annotation value of an annotation (`@Retention`) on an annotation (`@DialogFlags` in this example) that is annotated to the starting parameter (flags), a util in Metalava uses a long chain of resolution/conversion/lookup APIs in UAST.

In this PR, I mimicked similar use cases, and showcased why they need a fall-back [util](https://cs.android.com/android/platform/superproject/+/master:tools/metalava/src/main/java/com/android/tools/metalava/ExtractAnnotations.kt;l=385;bpv=1) (to rely on PSI directly). Then, 2nd commit fixes resolution to enum entry declaration from library in UAST side. A fix in FIR UAST side is [KOTLIN-CR-226](https://kotlin.jetbrains.space/p/kotlin/reviews/226).

### CODE REVIEW

**Comment by jsjeon** [comment]
cc @xiexed for UAST change.

cc @darthorimar and @fedochet for FIR UAST changes.

**Comment by jsjeon** [comment]
Hm, github didn't pick up my force push for a long time. :\ Let me rebase and re-try. I may add one more commit that I found I missed previously.

**Comment by jsjeon** [comment]
@darthorimar FIR UAST/LC is broken in ToT of `kt-212-master` after property annotation retargeting: https://github.com/JetBrains/kotlin/commit/7243d3086914b82a396851dcad24b844a67727d2 I'll take a look at it and will send a CR in FIR LC side.

**Comment by jsjeon** [comment]
> @darthorimar FIR UAST/LC is broken in ToT of `kt-212-master` after property annotation retargeting: [JetBrains/kotlin@7243d30](https://github.com/JetBrains/kotlin/commit/7243d3086914b82a396851dcad24b844a67727d2) I'll take a look at it and will send a CR in FIR LC side.

[KOTLIN-CR-232](https://kotlin.jetbrains.space/p/kotlin/reviews/232/) will fix that, i.e., that one should go first.

**Comment by fedochet** [comment]
Thanks! The commits have been merged into the kt-212-master branch, they should appear in this repo soon

**Pull request closed without merging**
