### PR TITLE
Fix PyCustomMember.resolvesToClass

### PR DESCRIPTION
**Pull request by da1z**
Without the fix PyCustomMember.resolvesToClass(classQName) does not work properly.

new PyCustomMember(name).resolvesToClass(qName) wont resolve because it would use pass as a target class

### CODE REVIEW

**Comment by da1z** [comment]
@vlasovskikh please take a look at this

**Comment by vlasovskikh** [comment]
@da1z @fitermay Thanks for adding a test! Could you please add a call to `PyCustomMember.resolvesToClass(classQName)` to the test? It was mentioned by @da1z as the incentive for this PR.

Please squash all your commits into one. We strongly prefer that PRs don't contain any merge commits as they have been proven difficult to rebase.

**Comment by fitermay** [comment]
@vlasovskikh: Done

**Comment by vlasovskikh** [comment]
@da1z @fitermay Thanks for your PR! I've rebased it onto master.

**Pull request closed without merging**
