### PR TITLE
KTIJ-20486 False Positive Redundant Companion reference in extension function when accessing the same name property in extension and companion receivers

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-20486

### CODE REVIEW

**Comment by nikitabobko** [comment]
Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix them all or share your results as a comment.

**Comment by t-kameyama** [comment]
> Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix all the warnings introduced by the inspection (in separate commit but in this PR) or share your results as a comment.

Found nothing.

**Comment by t-kameyama** [comment]
Fixed 01c17a12a4a9

**Comment by t-kameyama** [comment]
Fixed. 01c17a12a4a9

**Pull request closed without merging**
