### PR TITLE
KTIJ-20509 False positive "Unused symbol" for unused in source code primary constructor parameter of value (inline) class

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-20509

### CODE REVIEW

**Comment by nikitabobko** [comment]
Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix them all or share your results as a comment.

**Comment by t-kameyama** [comment]
> the entire `intellij-community`

The inspection didn't find unused value classses in the intellij-community.

**Comment by t-kameyama** [comment]
> Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix all the warnings introduced by the inspection (in separate commit but in this PR) or share your results as a comment.

The inspection didn't find unused value classses in the intellij-community.

**Review by nikitabobko — APPROVED** [review]
The PR will be automatically merged once it passes all the tests on CI.

Additional fix:
```
diff --git a/community/plugins/kotlin/idea/tests/testData/inspectionsLocal/unusedSymbol/valueClassParameter.kt b/community/plugins/kotlin/idea/tests/testData/inspectionsLocal/unusedSymbol/valueClassParameter.kt
index 1074d36b18672..c51b0ae4436b0 100644
--- a/community/plugins/kotlin/idea/tests/testData/inspectionsLocal/unusedSymbol/valueClassParameter.kt
+++ b/community/plugins/kotlin/idea/tests/testData/inspectionsLocal/unusedSymbol/valueClassParameter.kt
@@ -1,17 +1,4 @@
 // PROBLEM: none
 // WITH_STDLIB
 @JvmInline
-value class V internal constructor(private val <caret>value: Int) {
-    companion object {
-        val Foo = V(0)
-        val Bar = V(1)
-        val Baz = V(2)
-    }
-
-    override fun toString() = when (this) {
-        Foo -> "Foo"
-        Bar -> "Bar"
-        Baz -> "Baz"
-        else -> ""
-    }
-}
+value class V internal constructor(private val <caret>value: Int)
```

**Pull request closed without merging**
