### PR TITLE
[IDEA-247100] Add support for JDKs installed by asdf-java

### PR DESCRIPTION
**Pull request by joschi**
Additionally to JDKs installed by SDKMAN!, IDEA now also discovers JDKs installed by asdf-java.

https://youtrack.jetbrains.com/issue/IDEA-247100

### CODE REVIEW

**Comment by leo-from-spb** [comment]
Hello Jochen! Sorry for long delay.
I've merged your change manually. Thank you for the contribution!

**Comment by joschi** [comment]
Thanks for merging! 😃

For reference: a921c9fd7cbba809d7ea3cb0846af18428054e51

**Comment by myjohndoeside** [comment]
Can somebody confirm that this still works in 2022.1.1 release?
Mine doesn't display any of the JDKs installed by asdf, I still have to manually add them.

Or is there a specific asdf command that I need to run first?

**Comment by myjohndoeside** [comment]
Can somebody confirm that this still works in 2022.1.1 release?
Mine doesn't display any of the JDKs installed by asdf, I still have to manually add them.

Or is there a specific asdf command that I need to run first?

**Comment by joschi** [comment]
@myjohndoeside See https://youtrack.jetbrains.com/issue/IDEA-292847 and https://github.com/JetBrains/intellij-community/pull/2031. 😄

**Pull request closed without merging**
