### PR TITLE
IDEA-257690 Add settings for validation of branch name

### PR DESCRIPTION
**Pull request by MitchyGoodness**
Add to the Settings menu, under Version Control | Git | Branching:
* Checkbox to toggle if validation runs
* Dropdown to select the string used to replace invalid branch name entries
  * Replacement strings selectable are an empty string, hyphen, or underscore
* Checkbox to toggle if branch name is converted to lower case
* Dropdown to select the maximum number of consecutive underscores allowed

Add checkbox to toggle if validation runs to the new branch name dialog.

### CODE REVIEW

**Comment by MitchyGoodness** [comment]
Hey @dmitriysmirnovjb, I forgot to add tests for `git4idea.validators.GitRefNameValidator#cleanUpBranchNameOnTyping` in `git4idea.config.GitRefNameValidatorSettingsTest`. I'll add a commit for that change a little later today.

**Comment by Mattwmaster58** [comment]
Would love to see this merged, would be a great QoL improvement. Anything specific holding this back @dmitriysmirnovjb ?

**Comment by Radek-Pysny** [comment]
Good day, do we have any update on this one? Will it get merged some day? Thanks for info in advance.

**Comment by MitchyGoodness** [comment]
Hey @ybedrov and @dmitriysmirnovjb, do you need me to resolve conflicts, or adhere to a requirement before this can be merged? I would like to see this merged in, since it impacts my workflow.

**Comment by reseto** [comment]
@MitchyGoodness you are godsent! Could you please resolve conflicts so that admins can merge? 
There are 6 different tracked issues and a bunch of twitter posts wanting this feature. [IDEA-257690 nicknamed To Hell with underscores](https://youtrack.jetbrains.com/issue/IDEA-257690/Add-the-ability-to-tweak-automatic-conversion-settings-for-Create-New-Branch)
Our entire team would be super happy to get this feature.

**Comment by MitchyGoodness** [comment]
@reseto sorry for the wait! The conflict has been resolved.

**Comment by AlexBsrd** [comment]
Hi,
Any news on the release date of this feature ? 
We are very looking forward to use this feature in our company 👀

**Comment by MitchyGoodness** [comment]
Issue fixed by Dmitriy Smirnov

**Pull request closed without merging**
