### PR TITLE
Fix WM_CLASS x property not being null-terminated

### PR DESCRIPTION
**Pull request by Yannik**
The WM_CLASS must be null-terminated according to the icccm spec 4.1.2.5:

>  The WM_CLASS property (of type STRING without control characters) contains two consecutive null-terminated strings. These specify the Instance and Class names to be used by both the client and the window manager for looking up resources for the application or as identifying information. This property must be present when the window leaves the Withdrawn state and may be changed only while the window is in the Withdrawn state. Window managers may examine the property only when they start up and when the window leaves the Withdrawn state, but there should be no need for a client to change its state dynamically.

https://tronche.com/gui/x/icccm/sec-4.html

This fixes the icon for the jetbrains IDEs appearing twice due to random memory being added to the WM_CLASS because it missed the null-terminator. This happened for example in the gnome launcher.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by Yannik** [comment]
@klikh Are you sure it's necessary to sign a 1-2 page legal paper to contribute a 2 line change?
I will gladly state that I waive all my rights to these 2 lines here on github.

**Comment by trespasserw** [comment]
`WM_CLASS` is assembled from an array, and the value of `awtAppClassName` field isn't always the second part of the pair. So, thank you for pointing to a problem, but I cannot accept the fix as-is, sorry. I'll submit a patch for inclusion in our build of JDK, and hopefully upstream to Oracle.

**Comment by trespasserw** [comment]
In fact, the bug is already fixed by Oracle, scheduled for 8u82 (see [JDK-6961123](https://bugs.openjdk.java.net/browse/JDK-6961123) for details).

**Comment by Yannik** [comment]
@trespasserw 

As 8u82 will only be released in July 2016 (see https://bugs.openjdk.java.net/projects/JDK/versions/18319), it would be good to fix this now. 

I've been using the patch I submitted here in production without any issues - can you give clearer references to the issues you are expecting to happen here?

**Comment by trespasserw** [comment]
Right, that's why we'll port the fix to our custom JDK ASAP.

The problem is, at early stages, WM_CLASS would be in a "name\0\0name\0" format. I'm not sure this won't break any other WMs.

**Pull request closed without merging**
