### PR TITLE
Use HTTPS for critical-startup-errors URL

### PR DESCRIPTION
**Pull request by bdukes**
I noticed this error was using HTTP in the URL, but HTTPS is supported for this domain. Hope it helps!

### CODE REVIEW

**Comment by rosti-il** [comment]
Interesting that opening the http://jb.gg/ide/critical-startup-errors in a browser makes two redirects: (1) into the same URL but with HTTPS and then (2) into https://intellij-support.jetbrains.com/hc/en-us/articles/360007568559 that is also HTTPS. So opening [http**s**://jb.gg/ide/critical-startup-errors](https://jb.gg/ide/critical-startup-errors) i.e. with HTTPS in the first place makes one redirect less.

On the other hand the jb.gg is hosted at Amazon cloud and using it with the HTTPS (the first redirection) just for redirections to the JetBrains site (the second redirection) seems like an over-engineering. Could it be configured at Amazon cloud to make such redirections straight forward?

**Comment by VladRassokhin** [comment]
>seems like an over-engineering
Contrariwise, it's just two separated simple logic blocks: 1 - convert all http to https; 2 - redirect to actual site. First block is used not only here and it's natural to reuse it.

Instead of creating another logic of redirecting http to external site it's safer and proper to get rid of http links in first place, that's done in this PR. Once merged, there would be only one redirect.

**Comment by rosti-il** [comment]
Then you should change the URL in the https://intellij-support.jetbrains.com/hc/en-us/articles/360007568559 article as well.

**Comment by ant-druha** [comment]
@rosti-il done, thank you.

**Pull request closed without merging**
