### PR TITLE
Fix the issue when debugger is stuck in an infinite loop in Android project

### PR DESCRIPTION
**Pull request by nikita-nazarov**
Related issue: https://youtrack.jetbrains.com/issue/KTIJ-24259/Debugger-is-stuck-in-an-infinite-loop-in-an-Android-project

It could happen that the `replacements` map for an arbitrary key contained a value that is equal to that key. This resulted in an infinite loop, which affected all the debugger behaviour.

### CODE REVIEW

**Comment by madsager** [comment]
@sfs you should have a look at this one.

**Comment by yanex** [comment]
Is it possible to add some test?

**Comment by sfs** [comment]
Yes, the tests are in a separate PR (https://github.com/JetBrains/intellij-community/pull/2300), which I'll have to rebase once this PR is merged. Alternatively we could close that PR and cherry pick the tests into this one if that's preferable?

**Comment by yanex** [comment]
Several tests failed because of the change.
Screen Shot 2023-01-25 at 0 18 16

```
java.lang.NullPointerException: Cannot invoke "com.jetbrains.jdi.VirtualMachineImpl.equals(Object)" because "this.vm" is null
  at com.jetbrains.jdi.MirrorImpl.equals(MirrorImpl.java:66)
  at com.jetbrains.jdi.LocalVariableImpl.equals(LocalVariableImpl.java:87)
  at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:169)
  at org.jetbrains.kotlin.idea.debugger.core.StackFrameUtilsKt.sortedVariablesWithLocation(stackFrameUtils.kt:96)
  at org.jetbrains.kotlin.idea.debugger.test.dex.AbstractLocalVariableTableTest.doLocalVariableTableComparisonTest(AbstractLocalVariableTableTest.kt:42)
  at org.jetbrains.kotlin.idea.debugger.test.dex.DexLocalVariableTableComparisonTest.testDelegatedPropertyGeneratorGenerateDelegatedProperty(DexLocalVariableTableComparisonTest.kt:2296)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at junit.framework.TestCase.runTest(TestCase.java:177)
  at junit.framework.TestCase.runBare(TestCase.java:142)
  at junit.framework.TestResult$1.protect(TestResult.java:122)
  at junit.framework.TestResult.runProtected(TestResult.java:142)
  at junit.framework.TestResult.run(TestResult.java:125)
  at junit.framework.TestCase.run(TestCase.java:130)
  at junit.framework.TestSuite.runTest(TestSuite.java:241)
  at junit.framework.TestSuite.run(TestSuite.java:236)
  at com.intellij.TestAll.runNextTest(TestAll.java:347)
  at com.intellij.TestAll.run(TestAll.java:273)
  at junit.framework.TestSuite.runTest(TestSuite.java:241)
  at junit.framework.TestSuite.run(TestSuite.java:236)
  at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
  at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
  at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
  at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
  at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
  at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
  at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
  at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
  at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
  at com.intellij.tests.JUnit5TeamCityRunnerForTestAllSuite.main(JUnit5TeamCityRunnerForTestAllSuite.java:48)
```

**Comment by yanex** [comment]
Merged into `master` manually (https://github.com/JetBrains/intellij-community/commit/6a9767e3f9fdc36279c7cd6d4c3bb492747f67ae, https://github.com/JetBrains/intellij-community/commit/12f96dea92ed7b4b9acc1767271e4360128bee43). Thanks for the fix!

**Pull request closed without merging**
