### PR TITLE
Add Nullable for YAMLKeyValue::getParentMapping to sync it with YAMLKeyValueImpl

### PR DESCRIPTION
**Pull request by Haehnchen**
npe issue because of not seeing nullable return value: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/942

### CODE REVIEW

**Comment by ignatov** [comment]
@Haehnchen is it still valid?

**Comment by ignatov** [comment]
cc @valich

**Comment by valich** [comment]
This _is_ still actual. I've reviewed some of our usages of this method and found some newly appeared warnings. I've fixed them and also added "pure" contract to simplify checks/assertions.

@Haehnchen Thank you very much and sorry for the delay.

**Comment by valich** [comment]
Merged.

**Pull request closed without merging**
