### PR TITLE
Make data-sharing consent company-specific

### PR DESCRIPTION
**Pull request by dahlstrom-g**
Android Studio needs separate data-sharing consent described by
different language referring to Google and its privacy policy.

(cherry picked from commit d601c06)

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@eugenezh?

**Comment by dahlstrom-g** [comment]
@eugenezh?

**Comment by eugenezh** [comment]
Merged manually to master. The data on disk and bundled resource name is now vendor-specific, though I retained previous paths and names for JetBrains products for compatibility with already released versions.

Do you need these changes in 2017.x versions?

**Comment by dahlstrom-g** [comment]
> Do you need these changes in 2017.x versions?

Not necessarily. I believe the new consents system is in IDEA 2017.3.4 only; that release was merged into Android Studio 3.2 before Canary 2, and we made this change on our side.

**Pull request closed without merging**
