### PR TITLE
[IDEA-138776] Maven polyglot support

### PR DESCRIPTION
**Pull request by Randgalt**
Massive changes to support Maven Polyglot. I was flying blind with this. I hope I've done OK. Currently, only Groovy is supported but it will be easy to add others. Changes:

* maven32-server-impl is removed
* maven33-server-impl added
* Polyglot type added to Maven settings panel
* Everywhere "pom.xml" is referenced, polyglot methods are used instead
* maven-polyglot-converter module added which converts on disk format to standard XML for internal use

### CODE REVIEW

**Comment by yole** [comment]
Could you please remove .jps-build-data from your pull request?

**Comment by Randgalt** [comment]
ref IDEA-138776

**Comment by Randgalt** [comment]
removed

**Comment by Ribesg** [comment]
Seems like a nice first step!
Can't wait for this!

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by Randgalt** [comment]
I just emailed the signed agreement

**Comment by klikh** [comment]
CA received, thanks.

**Comment by Ribesg** [comment]
You should probably remove some unwanted changes like changing the Java version to 7 or adding CoffeeScript to `.idea/codeStyleSettings.xml`.

**Comment by Randgalt** [comment]
> You should probably remove some unwanted changes like 
> changing the Java version to 7 or adding CoffeeScript to .idea/codeStyleSettings.xml.

I started with master. Should I just remove these files?

**Comment by klikh** [comment]
> I started with master. Should I just remove these files?
You should remove *the changes in these files*, not the files themselves.

Note that these configuration files might have been changed not directly by you, but rather by IDEA which noticed changes in the Settings (e.g. if you modified the code style from the UI).

**Comment by Ribesg** [comment]
Yeah I'm not sure what changed the files, but what I'm sure of is that you didn't look at what you were commiting when you did the commit :P

**Comment by Randgalt** [comment]
Um, I looked at everything. But, I didn't know what was required. I'm not sure why the config files are in the repo. But, I'll remove the changes.

**Comment by cemo** [comment]
+1

**Comment by brcolow** [comment]
@Randgalt Could you possibly squash the 3 commits into one? That should help this get merged I would think, especially as a bunch of weird local config files were included in the first commit. If you need help with this let me know I can assist.

**Comment by Randgalt** [comment]
@brcolow what would help me is to know what files I should not have committed. I can revert whatever needs reverting and then sqaush the commits.

**Comment by brcolow** [comment]
@Randgalt I was referencing earlier comments, sorry, I am not familiar with the code base to know the difference - that would need input from someone who knows what's what in this project. I should have been clear when I said I could assist with the squashing only ;)

**Comment by neilellis** [comment]
Could someone from JetBrains take a look at this as it is clearly a popular feature request and we'd love to see it added.Thank you :smile_cat: !

**Comment by vasilievip** [comment]
+1

**Comment by vladsoroka** [comment]
Thanks for the contribution, however we can not merge this PR, since the feature was implemented slightly different.
You can try the feature using the nearest EAP (IDEA 2016.3 EAP build >= #163.4830.3).
Your feedback are welcome!

You can find the change at https://github.com/JetBrains/intellij-community/commit/a2c139bc61f57d167c7ce4918dbc32a1295a5788

**Comment by Randgalt** [comment]
No worries - this was a strawman proposal anyway.

**Pull request closed without merging**
