### PR TITLE
[gradle] Watch libs.versions.toml

### PR DESCRIPTION
**Pull request by fp7**
Issue: IDEA-293328

### CODE REVIEW

**Comment by HackerMadCat** [comment]
Thanks a lot! I'll try to pull it into master.

ps. It isn't full fix but it is better then nothing.
Gradle allows to defined any file as versions catalog.

**Comment by fp7** [comment]
@HackerMadCat I completed the fix and added tests for non default version catalogs.

**Comment by fp7** [comment]
@HackerMadCat Some news about merging this? I would be happy to invest some more time if this pr needs more work.

**Comment by HackerMadCat** [comment]
Commit: d66a302553533e341baeef0cee912856a6db5a25

**Pull request closed without merging**
