### PR TITLE
Fix loading of C native library on FreeBSD with JNA < 4.1.0.

### PR DESCRIPTION
**Pull request by alexdupre**
For reference: https://github.com/twall/jna/issues/279

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by alexdupre** [comment]
CLA submitted.

**Comment by klikh** [comment]
Received, thanks.

**Comment by alexdupre** [comment]
Actually I'm thinking it could make more sense to rebuild the old jna library with this patch: https://people.freebsd.org/~jkim/jna.diff
This would fix not only this issue, but also other libraries (pty4j, jtermios, etc.) that uses jna to load the libc. What's your opinion?

**Comment by trespasserw** [comment]
Sounds reasonable. Just need to check what holds us back from JNA upgrade.

**Comment by trespasserw** [comment]
Status update: we're in the process of migrating to JNA 4.1 - upgrading and checking dependent libraries one-by-one.

**Comment by trespasserw** [comment]
Finished the migration to JNA 4.1 (finally :/). Sorry for it to take so long.

**Pull request closed without merging**
