### PR TITLE
Added additional method to BudledKeymapProvider extension point to be…

### PR DESCRIPTION
**Pull request by da1z**
… able to load keymaps from InputStream

Need this because of if you are developing plugin using gradle-intellij-plugin it wont find keymap by file name

### CODE REVIEW

**Comment by yole** [comment]
How exactly are you specifying the name? If the keymap .xml file is correctly packaged in the plugin jar and if you specify its name correctly, the existing APIs are sufficient to load it. If not, you need to fix either your build script or your BundledKeymapProvider implementation. There is no need to extend the API.

**Comment by da1z** [comment]
i put my keymap.xml into resources/idea/ and my BundledKeymapProvider looks like

```
List<String> getKeymapFileNames() {
 return Collections.singletonList("keymap.xml");
}
```

and DefaultKeymap.java can not locate my keymap

**Comment by da1z** [comment]
The keymap loader uses the class loader of the URLUtil class, so it never delegates to the plugin classloader. So we either need to return a stream or else be able to specify the classloader to use in order for this extension point to work inside a plugin.

**Comment by yole** [comment]
This is indeed a problem that can be fixed, but it doesn't require adding any new APIs. It's possible to load the keymap .xml file from the classloader of the BundledKeymapProvider implementation class.

**Comment by da1z** [comment]
How? i can't find API for this. please give me a few lines example

**Comment by da1z** [comment]
Sent a new pull request. Please check this out https://github.com/JetBrains/intellij-community/pull/493

**Pull request closed without merging**
