### PR TITLE
Why is Google the search engine?

### PR DESCRIPTION
**Pull request by Hallowizer**
Ignore the commits attached to this. There's no issue button so I'm saying this here. Why is there a "Search with Google" button? Why would you promote such an invasive search engine? This is uncool. I'm not even able to change it to DuckDuckGo!

### CODE REVIEW

**Comment by ybedrov** [comment]
Could you please clarify what button do you mean?

**Comment by Hallowizer** [comment]
The one on the right click menu that appears when you select some text.

**Comment by ybedrov** [comment]
Please vote for the related request on YouTrack: https://youtrack.jetbrains.com/issue/IDEA-133410

**Comment by therealbluepandabear** [comment]
> The one on the right click menu that appears when you select some text.

I know I'm very late to this, but I've fought to get the issue added here: https://youtrack.jetbrains.com/issue/IDEA-289262

And, according to a member of JetBrains, this will be added soon:

image

**Pull request closed without merging**
