### PR TITLE
Allow debugger to work when Python is in isolated mode

### PR DESCRIPTION
**Pull request by gaborbernat**
See https://youtrack.jetbrains.com/issue/PY-45659 for more details.

### CODE REVIEW

**Comment by Elizaveta239** [comment]
@gaborbernat Thank you very much for the pull request!

**Comment by gaborbernat** [comment]
@Elizaveta239 shall we close this? I see has been pushed under a new commit?

**Comment by Elizaveta239** [comment]
Sure! Thank you very much for the contribution, it's merged to master

**Comment by gaborbernat** [comment]
thanks

**Comment by addisonklinke** [comment]
Still seeing this bug in PyCharm CE 2022.2.1

**Pull request closed without merging**
