### PR TITLE
IDEA-99003 Render type parameters in project view

### PR DESCRIPTION
**Pull request by VISTALL**

### CODE REVIEW

**Comment by ignatov** [comment]
Please update the PR.

**Comment by VISTALL** [comment]
Hello. I'm not interest in this PR anymore. Sorry

**Comment by naXa777** [comment]
the code in this PR is not touched since 2013. is it still useful? if yes -> please resolve the conflicts and merge. if no -> consider closing this PR.

@SergeyMalenkov

**Comment by anstarovoyt** [comment]
Thank you for creating this pull request and for your contribution to the IntelliJ platform. We would like to apologize for not acting on it sooner.
We reviewed the PR and decided not to merge it.
We are trying to keep the project view as clean as possible. Showing type parameters in the Project view might make it harder to navigate through the project files. Moreover, for classes with multiple type parameters, it's hard to present this information in a readable and actionable way.
Thank you for understanding. Please let us know if you have any questions or suggestions.

**Pull request closed without merging**
