### PR TITLE
KTIJ-19077 "Convert to enum class" intention on sealed interface generates "enum interface"

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-19077

### CODE REVIEW

**Comment by LouisCAD** [comment]
Isn't the sealed interface test data lacking the `: I` part? Also, why is the enum test data still hosting `object`s instead of enum entries?
Maybe I do not understand what is being tested?

**Comment by t-kameyama** [comment]
@LouisCAD Thanks!! I've fixed tests.

**Comment by LouisCAD** [comment]
Nit: there is a space on both sides of the `:` character when used for inheritance.

**Comment by klunnii** [comment]
1. Please move test data to `plugins/kotlin/idea/tests/testData/intentions/convertEnumToSealedClass`
2. `ConvertEnumToSealedClassIntention#applicabilityRange` checks an `element` has `class` keyword. But here it deals with `itnerface`. Intention doesn't seem to work.

**Comment by t-kameyama** [comment]
> * Please move test data to `plugins/kotlin/idea/tests/testData/intentions/convertEnumToSealedClass`
> * `ConvertEnumToSealedClassIntention#applicabilityRange` checks an `element` has `class` keyword. But here it deals with `itnerface`. Intention doesn't seem to work.

`Convert to enum class` is ConvertSealedClassToEnumIntention, not ConvertEnumToSealedClassIntention.

スクリーンショット 2021-07-13 12 49 35

**Comment by klunnii** [comment]
Please, disregard my previous comment. Everything is ok. Merged. Thank you!

**Pull request closed without merging**
