### PR TITLE
Fixed `FlipCommaIntention` for Groovy files

### PR DESCRIPTION
**Pull request by paplorinc**
### Before the fix:
```Groovy
def m(String a, int b, boolean c) {}
def m(String a  boolean c,, ,int b) {}
```
### After the fix:
```Groovy
def m(String a, int b, boolean c) {}
def m(String a, boolean c, int b) {}
```
### Before the fix:
```Groovy
[1, 2, 3]
[  3,2,1]
```
### After the fix:
```Groovy
[1, 2, 3]
[2, 1, 3]
```
I have checked that `Change signature` is still working.

@maxmedvedev, @ignatov

### CODE REVIEW

**Comment by dovchinnikov** [comment]
@paplorinc see GrIntentionTestCase and its inheritors for examples.

**Comment by paplorinc** [comment]
Thanks @dovchinnikov, will create a test for it soon :)

Could you please take a look at my other PRs in the meantime?

**Comment by dovchinnikov** [comment]
@paplorinc yeah, sure

**Comment by paplorinc** [comment]
@dovchinnikov, done, corrected the flip for lists also

**Comment by ignatov** [comment]
Merged manually, thanks.

**Pull request closed without merging**
