### PR TITLE
Remove final keyword from InvalidDataException

### PR DESCRIPTION
**Pull request by dahlstrom-g**
This was added incidentally by commit d504262
breaking compilation of existing subclasses.

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@develar? @SergeyZh?

**Comment by dahlstrom-g** [comment]
@develar, thanks for contributing to the discussion on related #1407. Can we go ahead with this one?

**Comment by develar** [comment]
Is it possible to not extend `InvalidDataException`? Where I can find usages to understand why extending is required?

**Comment by dahlstrom-g** [comment]
The uses are all in Firebase code which isn't public unfortunately.

I don't understand why the `final` modifier was added in commit d504262 in the first place. Is it related to that commit somehow? In any case, with regard to this [general rationale](https://github.com/JetBrains/intellij-community/pull/1407#issuecomment-655394757), `InvalidDataException` doesn't look like much of a maintenance burden given its current state and revision history.

**Comment by klikh** [comment]
Fixed in 96795c2b

**Comment by klikh** [comment]
I used the original hash here, but I forgot that it has been changed when the code was mirrored to GitHub. Sorry for that, glad that you've found the commit.

**Pull request closed without merging**
