### PR TITLE
kotlin formatting: space between string and lambda

### PR DESCRIPTION
**Pull request by phiSgr**

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
@phiSgr is there any particular [KTIJ](https://youtrack.jetbrains.com/issues/KTIJ) ticket ? 

Please check [CONTRIBUTING / What to contribute](https://github.com/JetBrains/intellij-community/blob/master/plugins/kotlin/CONTRIBUTING.md#2-what-to-contribute) guidelines.

**Comment by phiSgr** [comment]
I guess not. This is something quite niche that's been bothering me.

Did a quick search. Couldn't find a related ticket.

**Comment by vladimirdolzhenko** [comment]
It would be nice if you can create a ticket and describe reason behind the change.

**Comment by phiSgr** [comment]
https://youtrack.jetbrains.com/issue/KTIJ-20655

**Comment by vladimirdolzhenko** [comment]
Very interesting case. Thank you for the contribution.

**Pull request closed without merging**
