### PR TITLE
Fixed SVG Icon preview in the Gutter

### PR DESCRIPTION
**Pull request by mlytvyn**
Continuation of the change applied by `Aleksey Pivovarov 12/04/2018, 17:25 ui: support svg icons in editor gutter preview`
in scope of the `14b800ee91f81e6f3dead5a489c1d0255e890c9d`.
SVG images cannot be loaded directly from the file bytearray.

**before**
Screenshot 2023-04-09 at 17 10 33

----

**after**
Screenshot 2023-04-09 at 17 12 29
Screenshot 2023-04-09 at 17 14 33

### CODE REVIEW

**Comment by mlytvyn** [comment]
@karollewandowski , updated with latest `master`

**Comment by bric3** [comment]
@mlytvyn Would that work for third party plugins. And for their own `MyPluginIcon` class ?

**Comment by mlytvyn** [comment]
@bric3 , assume so, as it worked well for 3rd-party plugin `HybrisIcons.java` class, not only for `AllIcons.java`

**Comment by bric3** [comment]
Cool thanks for the confirmation.

**Comment by bric3** [comment]
Could it work if is a kotlin class `MyPluginIcon.kt`.

**Comment by mlytvyn** [comment]
@develar , any change this PR will be merged and included in the next release?

**Comment by bric3** [comment]
Any news on this one ?

**Pull request closed without merging**
