### PR TITLE
Add a Way To Specify Class Names to Not Import Inner Classes For

### PR DESCRIPTION
**Pull request by alonalbert**
Like Builder, Factory etc

https://youtrack.jetbrains.com/issue/IDEA-135092

### CODE REVIEW

**Comment by alonalbert** [comment]
1 picker
2 setting
3 imports outer class
4 imports inner class

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by alonalbert** [comment]
Kirill

I work at Google and according to our Open SOurce policy, the patch I submit should associated to my @google.com address.
I created a new PR 
https://github.com/JetBrains/intellij-community/pull/828
And signed the CLA with my @google.com email.
Can you please use the other PR instead of this one?

**Comment by klikh** [comment]
Btw, as a Google employee, you didn't need to sign a CLA, since we've got a special agreement between JetBrains and Google.

**Pull request closed without merging**
