### PR TITLE
IDEA-138533 Add checkbox to disable Maven keyboard shortcuts

### PR DESCRIPTION
**Pull request by klassm**
See https://youtrack.jetbrains.com/issue/IDEA-138533 for reference. Having loads of Maven modules causes the IDE to freeze. Not loading the keyboard shortcuts will solve this problem.

Thanks,
Matthias

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by klassm** [comment]
@klikh ok, done

**Comment by klikh** [comment]
Agreement received, thanks.

**Comment by klassm** [comment]
@klikh Is there anything I can do to help you merge this issue?
Thanks,
Matthias

**Comment by klikh** [comment]
@klassm The fix will be reviewed by our Maven specialist soon.

Btw, in general personally I'm against introducing options to the UI to fix performance problems. Maybe there is some other way to fix it. But I'm not familiar with this problem well enough, it is just a wild guess.

**Comment by klassm** [comment]
For sure, I understand your point - I would be happy to have any other solution to the problem. Currently, the keymap and all the search functionality within the preferences window is absolutely unusable.
Any chance to get your Maven specialist look into this any time soon :-)?

**Comment by vladsoroka** [comment]
Hi Matthias, thanks for your time spent for the contribution!
However we will not merge this pull request in favour of another fix, it retains (in a Keymap) only maven actions with a shortcut assigned. 
You can find the CL at https://upsource.jetbrains.com/idea-community/revision/a6d103fa25185d864b810933a18ea163e1870389

**Comment by klassm** [comment]
Yip that's perfectly ok for me. Thanks for the fix!

**Pull request closed without merging**
