### PR TITLE
Handle Note Javac output lines

### PR DESCRIPTION
**Pull request by dansanduleac**
## Before this PR

In the javac output produced by gradle, "Note" log lines like

```
<file path>:<line number>: Note: ...
```

get interpreted as errors when compiling through gradle (either by running `classes` as a task, or having the Gradle integration configured to "Build and run using" Gradle.

It's doubly annoying because it also jumps the editor to the first "error" whenever I build.

image

These types of messages come up when compiling using the errorprone compiler, and you get a hit on an errorprone check with severity [SUGGESTION](https://github.com/google/error-prone/blob/v2.3.4/annotation/src/main/java/com/google/errorprone/BugPattern.java#L171).

## After this PR

Javac output lines of the shape `<file>:<line>: Note:` get interpreted as as info messages in the structured output when compiling with gradle.

### CODE REVIEW

**Comment by ybedrov** [comment]
Hello!
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by dansanduleac** [comment]
@ybedrov done

**Comment by dansanduleac** [comment]
@ybedrov any blockers for merging this?

**Comment by vladsoroka** [comment]
Thank you for the contribution! 
The change has been merged.

**Pull request closed without merging**
