### PR TITLE
override SmartList.equals() for better performance

### PR DESCRIPTION
**Pull request by stsypanov**
Default implementation of AbstractList.equals() creates two Iterators and then compare their items one by one. For array-base implementations (ArrayList/SmartList) it's possible to enhance comparison by
1) comparing sizes
2) if lists have the same size then we can use get(i) instead of iterators

### CODE REVIEW

**Comment by donnerpeter** [comment]
Why, is there any specific performance problem you're trying to address with this change?

**Comment by stsypanov** [comment]
I've found 174 usages of List.equals() in the code of Idea CE where concrete instance of List is ArrayList. Changing ArrayList into SmartList probably gives some performance improvement supposing this patch is applied.

**Comment by stsypanov** [comment]
Is it possible to exclude other commits from this pull-request or should I create new one?

**Comment by donnerpeter** [comment]
Merged

**Pull request closed without merging**
