### PR TITLE
Fixed issues with Jump to source/ Jump to Type in python debugger

### PR DESCRIPTION
**Pull request by fitermay**
--Fixed issue with jump to type not working unless type is imported directly in the scope. Usually the type won't be imported in the scope, so it wasn't working in the common case
--Added support for jump to type, jump to source for frames other than the topmost frame
--Fixed issue with jump to source not working if the element is a module name

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by fitermay** [comment]
Sent

**Comment by klikh** [comment]
Received, thanks.

**Comment by Elizaveta239** [comment]
@filtermay Thank you for the pull request! Could you please provide an example which shows  
the functionality added by these changes?

**Comment by fitermay** [comment]
Example:
---module A:
import module_b
foo_object = module_b.make_foo()
print (foo_object.field_1) #put breakpoint on this line

--module B:
class FooClass(object):
    def __init__(self):
        super(FooClass, self).__init__()
        self.field_1 = 42
        self.field_2 = 46

def make_foo():
    return FooClass()

In variables view select foo_object, jump to _type_source
Behavior before: Doesn't work because FooClass is not imported directly (actually most common case)
Behavior with change: Jumps to FooClass declaration

In variables view select foo_object-> field_1, jump to source
Behavior before: Doesn't work because field_1 is inside inner frame
Behavior with change: Jumps to field_1 assignment in the constructor

In variables view select module_b-> FooClass, jump to type source
Behavior before: Goes to the 'type' type which is useless
Behavior with change: Jumps to 'FooClass'

**Comment by Elizaveta239** [comment]
It looks very nice! 
Some Java code style remarks: please, always use braces even in single statement if-blocks and leave the brace at the end of the line.

**Comment by fitermay** [comment]
Sorry, forgot to reformat before push. I assume you can reformat after merging?

**Comment by Elizaveta239** [comment]
Yes, of course.

**Pull request merged**
