### PR TITLE
Unintended autocomplete when typing B or P in Kotlin

### PR DESCRIPTION
**Pull request by goodwinnk**
Fix for https://youtrack.jetbrains.com/issue/KT-8474.

### CODE REVIEW

**Comment by donnerpeter** [comment]
I'd say:
1. The platform shouldn't have Kotlin reference here (or should have references to all other possible languages for symmetry, which is infeasible)
2. Surround (and maybe others) templates shouldn't be shown in autopopup completion list and selected by keys they're not assigned to. @zolotov ?

**Comment by goodwinnk** [comment]
1. I completely agree there shouldn't be references to particular languages but think that under current architecture this fix is a valid cure for a long-standing problem.
2. Also true, the whole feature looks questionable to me.

**Comment by zolotov** [comment]
2. not sure about this. Surround templates are not any different to regular templates. The fact that they have a `$SELECTION$` variable is just a nice bonus.

I'd say we need to rethink `OTHER` context type. Why `Kotlin` context matches `Other` context type?

**Comment by zolotov** [comment]
There was a suggestion by Peter do not show templates in auto popup if there is nothing but them. I'm still not sure about it but I'll try to implement it

**Pull request closed without merging**
