### PR TITLE
[IDEA-252000] Update firefox icon

### PR DESCRIPTION
**Pull request by KotlinIsland**
Sourced from [here](https://mozilla.design/firefox/logos-usage/#content:~:text=Firefox%20browser%20logos) [download link](https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Firefox-Browser-Logo-Assets.zip)

### CODE REVIEW

**Comment by KotlinIsland** [comment]
Can you please tag this pr with `hacktoberfest-accepted`

**Comment by bulenkov** [comment]
@KotlinIsland the archive is missing the LICENSE file. What license these icons have?

**Comment by DetachHead** [comment]
i believe a license is not necessary according to this
https://www.mozilla.org/en-US/foundation/trademarks/policy/
image

**Comment by bulenkov** [comment]
@DetachHead thanks! I have converted the icon to 16x16 viewbox and also updated Firefox developer icon

**Pull request closed without merging**
