### PR TITLE
fortify GitLogParser to fix IDEA-128280

### PR DESCRIPTION
**Pull request by ostafiychuk**
Description of the problem: [IDEA-128280](https://youtrack.jetbrains.com/issue/IDEA-128280)
GitLogParserTest tests passed

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by rostafiychuk** [comment]
@klikh done

**Comment by ostafiychuk** [comment]
@klikh did it yesterday

**Comment by ostafiychuk** [comment]
@klikh can you review this?

**Comment by klikh** [comment]
Agreement received. Thank you. Will review the patch shortly.

**Comment by ostafiychuk** [comment]
Can this be cherry-picked to 14.1 branch if patch is OK?

**Comment by klikh** [comment]
Sorry for delay.

The problem with the patch is that it only works around the `^A` character (`\u0001`). `\u0002` characters are not handled (which is OK since they are not handled in the current version either). 
But what is worse is that the patch breaks the parser if `\u0003` is found in the commit message (while in the current version this character is handled fine).

**Comment by klikh** [comment]
Fixing the parser so that it would survive against any characters in the commit message seems to be kinda tricky. 

Here is a way I'm thinking about:
* surround the commit message by some other data which can't contain such characters for sure (e.g. always get <hash><subject><parents><body><commit date>)
* get rid of the RECORD_END flag.
* look for the next RECORD_START flag, but accept it only if the next token looks like a hash or is absent.
* while parsing record's items, 

What do you think about it? Do you have any better ideas? 
Maybe something not 100% reliable, but requiring less changes & not worse than the current version (so that we could more safely backport it to 14.1)?

**Comment by rostafiychuk** [comment]
I tried to replace `\u0001` with `\u0003` in commit message and get:
```
[  45223]  ERROR - plication.impl.ApplicationImpl - bad hash string: #
 
java.lang.IllegalArgumentException: bad hash string: #

	at com.intellij.vcs.log.impl.HashImpl.parseChar(HashImpl.java:79)
	at com.intellij.vcs.log.impl.HashImpl.buildData(HashImpl.java:66)
	at com.intellij.vcs.log.impl.HashImpl.build(HashImpl.java:41)
	at git4idea.history.GitHistoryUtils.createCommit(GitHistoryUtils.java:844)
	at git4idea.history.GitHistoryUtils.access$400(GitHistoryUtils.java:68)
	at git4idea.history.GitHistoryUtils$11.fun(GitHistoryUtils.java:763)
	at git4idea.history.GitHistoryUtils$11.fun(GitHistoryUtils.java:759)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1781)
	at git4idea.history.GitHistoryUtils.loadDetails(GitHistoryUtils.java:836)
	at git4idea.history.GitHistoryUtils.loadMetadata(GitHistoryUtils.java:758)
	at git4idea.log.GitLogProvider.readFirstBlock(GitLogProvider.java:105)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$3.each(VcsLogRefresherImpl.java:123)
...
```

so `\u0003` is not handled now.

**Comment by ostafiychuk** [comment]
I tried to replace `\u0001` with `\u0003` in commit message and get:
```
[  45223]  ERROR - plication.impl.ApplicationImpl - bad hash string: #
 
java.lang.IllegalArgumentException: bad hash string: #

	at com.intellij.vcs.log.impl.HashImpl.parseChar(HashImpl.java:79)
	at com.intellij.vcs.log.impl.HashImpl.buildData(HashImpl.java:66)
	at com.intellij.vcs.log.impl.HashImpl.build(HashImpl.java:41)
	at git4idea.history.GitHistoryUtils.createCommit(GitHistoryUtils.java:844)
	at git4idea.history.GitHistoryUtils.access$400(GitHistoryUtils.java:68)
	at git4idea.history.GitHistoryUtils$11.fun(GitHistoryUtils.java:763)
	at git4idea.history.GitHistoryUtils$11.fun(GitHistoryUtils.java:759)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1781)
	at git4idea.history.GitHistoryUtils.loadDetails(GitHistoryUtils.java:836)
	at git4idea.history.GitHistoryUtils.loadMetadata(GitHistoryUtils.java:758)
	at git4idea.log.GitLogProvider.readFirstBlock(GitLogProvider.java:105)
	at com.intellij.vcs.log.data.VcsLogRefresherImpl$3.each(VcsLogRefresherImpl.java:123)
...
```

so `\u0003` is not handled now too

**Comment by klikh** [comment]
Hm. I don't get this error: log opens without problems for me when commit message has `\u0003` in it. Note that according to the code it shouldn't fail either.

**Comment by ostafiychuk** [comment]
New patch works with both `\u0001` and `\u0003`. Splitted part will be concatenated with next one if it doesn't match `ONE_RECORD`

**Comment by klikh** [comment]
This one is nice. I've wrote a couple of tests against these situations and applied the patch.

Note that it still doesn't cover some exotic situations, e.g. if both `\u0001` and `\u0003` are found in the commit message, but anyway it is not worse than the current situation.

Let's keep the change in master branch for several days, and if no problems are found I'll backport it to 141, so that it gets into 14.1.2. Thanks for you contribution!

**Pull request closed without merging**
