### PR TITLE
[IDEA-123039] Use non-recursive Xalan str:tokenize() extension function instead of the recursive XSLT 1.0 hack

### PR DESCRIPTION
**Pull request by rosti-il**
This fixes the IDEA-123039 bug.

For more information about Xalan EXSLT extensions go to:
https://xalan.apache.org/xalan-j/extensionslib.html#exslt

### CODE REVIEW

**Comment by smoczyna** [comment]
that's lovely but it would be even better if you'd put add some guidelines how to do this.

**Comment by rosti-il** [comment]
@smoczyna, how to do what? I don't really understand your statement.
I've provided the fix and now @akozlova from JetBrains should review and merge it.

**Comment by smoczyna** [comment]
How to "use" xalan instead of other one of course. I have no clue how to do
that.

**Comment by rosti-il** [comment]
@smoczyna, take a look at the changes of this pull request and stop trolling. PR contains changes in the code, not only a title that you don't understand.

**Comment by smoczyna** [comment]
Look you rosti or perhaps rusty dickhead. I've been directed here by JetBrain support to get the solution of my problem which is exactly the same. However there is not any "solution" here I can use straight away, thus my comment.

**Comment by akozlova** [comment]
Sorry for late response. PR is merged manually, the fix should appear in the second 2019.1 EAP

**Pull request closed without merging**
