### PR TITLE
IDEA-158882 Adding support for setting.xml set via .mvn/maven.config

### PR DESCRIPTION
**Pull request by thorntonrp**
Maven 3.3 provides support for supplying project-specific maven execution arguments via `.mvn/maven.config` under the project base directory. This patch address issue IDEA-158882 to honors the `--settings` or `-s` argument supplied in that file.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please check your inbox: I've just send there the CLA to sign. Thanks.

**Comment by thorntonrp** [comment]
I Just faxed the CLA. Thanks.

**Comment by klikh** [comment]
Received, thanks.

**Comment by vladsoroka** [comment]
It seems the fix is not complete, it's just an illustration of needed support. The settings.xml set via .mvn/maven.config actually is not used for the project import, am I right or I miss something?

**Pull request closed without merging**
