### PR TITLE
Scopes Settings: Align files colors when added to scope

### PR DESCRIPTION
**Pull request by alexey-anufriev**
**Requirements**
- existing scope with assigned color to it
- non-empty project tree
- any file opened in the editor

**Problem**
When the opened file is assigned to scope and settings are saved then the color of a file is updated in the tree but the tab color of this file stays the same.

**Fix**
Now files tabs and the project tree are updated simultaneously.

### CODE REVIEW

**Comment by alexey-anufriev** [comment]
@akozlova, hi, is there any feedback on this change?

**Comment by alexey-anufriev** [comment]
hello @akozlova, any updates here?

**Review by akozlova — COMMENTED** [review]
> hello @akozlova, any updates here?

**Comment by alexey-anufriev** [comment]
Ok, let's try with a problem. I change the color attached to a scope, but opened files from this scope do not change the colors of related tabs. If my solution is not right, then could you suggest something else?

**Comment by akozlova** [comment]
I suggested the solution some months ago in the comment:
>so you would call project view refresh for each modified scope? Looks incorrect to me. If do refresh (and updateFilePresentation of cause as well!), then in com.intellij.ide.util.scopeChooser.ScopeChooserConfigurable#apply (it would be done once at least).

**Comment by alexey-anufriev** [comment]
> I suggested the solution some months ago in the comment:
> 
> > so you would call project view refresh for each modified scope? Looks incorrect to me. If do refresh (and updateFilePresentation of cause as well!), then in com.intellij.ide.util.scopeChooser.ScopeChooserConfigurable#apply (it would be done once at least).

Updated according to your suggestion.

**Comment by akozlova** [comment]
Have you submitted the contributor agreement? Please visit `https://www.jetbrains.com/agreements/cla/`. Thanks

**Comment by alexey-anufriev** [comment]
> Have you submitted the contributor agreement? Please visit `https://www.jetbrains.com/agreements/cla/`. Thanks

Done. I think the confusion came from the git log, where I used a mix of old and new emails.
But now I have signed the CLA for both so must be fine.

**Comment by akozlova** [comment]
merged manually, thanks

**Comment by alexey-anufriev** [comment]
Awesome! Thank you!

**Pull request closed without merging**
