### PR TITLE
Fix POP2 opcode handling bug with two category 1 values at the stack top.

### PR DESCRIPTION
**Pull request by Maccimo**
Decompiler has bug in handling POP2 opcode when two top values belong to category 1 (JVMS9 &sect;2.11.1)

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by Maccimo** [comment]
Done.

**Comment by gorrus** [comment]
Hi, do you have a test case for this?

**Comment by Maccimo** [comment]
13 out of 14 files in this commit is a parts of added testcases.
See testPop2* in SingleClassesTest.java

**Comment by gorrus** [comment]
Ups, sorry, I did not notice :)

**Comment by gorrus** [comment]
merged, thanks!

**Pull request closed without merging**
