### PR TITLE
KTIJ-18835 Completion: missed curly braces with labeled object (qualified this) in string template  

### PR DESCRIPTION
**Pull request by gyoussef55**
https://youtrack.jetbrains.com/issue/KTIJ-18835/Completion-missed-curly-braces-with-labeled-object-qualified-this-in-string-template

https://youtrack.jetbrains.com/issue/KTIJ-21663/Label-autocomplete-in-string-template-doesnt-add-curly-braces

https://youtrack.jetbrains.com/issue/KTIJ-24709/String-template-autocomplete-doesnt-work-with-qualified-this.

### CODE REVIEW

**Comment by abelkov** [comment]
Please add tests

**Comment by gyoussef55** [comment]
done

**Comment by vladimirdolzhenko** [comment]
@gyoussef55 could you pls rebase it on the latest master branch?

**Comment by vladimirdolzhenko** [comment]
I have to close it as no any feedback

**Pull request closed without merging**
