### PR TITLE
Add multi-language support for "Analyze Data Flow To/From Here"

### PR DESCRIPTION
**Pull request by asedunov**
The immediate goal is to allow mixing Java and Kotlin code in the same data flow graph as well as support grouping by leaf expressions and nullability (see also https://youtrack.jetbrains.com/issue/KT-16833)

### CODE REVIEW

**Comment by nicity** [comment]
Thank you for your contribution! I'd expect some tests present in the PR though

**Comment by asedunov** [comment]
As far as I see there no alternative dataflow implementations at the moment. So I don't think any new tests are necessary as single-language dataflow shouldn't be affected by these changes. Tests corresponding to the mixed Java-Kotlin dataflow will be added in the Kotlin project, though

**Comment by aborg0** [comment]
(A similar one for Scala: https://youtrack.jetbrains.com/issue/SCL-2818. Thanks for working on it.) @asedunov do you have plans to implement that for Scala too?

**Comment by asedunov** [comment]
@aborg0: Thanks. Currently I don't plan working on Scala implementation. The main objective of this PR was to add support for Java-Kotlin cross-language dataflow analysis. Groovy implementation is added mainly for the testing purposes

**Comment by aborg0** [comment]
@asedunov Thanks, in this case I'll add Scala. Once a version of this PR gets merged, I'll start working on it (as I do not want to duplicate your work and this is not urgent for me).
Thanks for rebasing your changes, I'll try to check it during the weekend (or just pull from the main repo if it gets merged ;) ).
Is there anything I can help?

**Comment by yole** [comment]
Merged manually.

**Pull request closed without merging**
