### PR TITLE
Add flake8 inspection supressor

### PR DESCRIPTION
**Pull request by jansorg**
This adds my inspection suppressor at https://github.com/jansorg/pycharm-flake8 to the PyCharm community sources, as requested by the PyCharm team.

### CODE REVIEW

**Comment by jansorg** [comment]
@east825 Is it still likely that the flake8 changes will be merged into intellij-community?

**Comment by east825** [comment]
Yes, sure! Sorry for this awful delay. There were some performance and applicability scope concerns because of which we decided not to include them in master right away. These changes together with further tweaks are still on an internal review. We will get back to them soon as we're approaching 2019.2 release. Once again, sorry for keeping you waiting 😓

**Comment by east825** [comment]
@jansorg [Integrated](https://github.com/JetBrains/intellij-community/commit/069e2acbc57cd8ef8205b5d568685f4e525dd75e) into upcoming 2020.1! @jansorg Thank you for your contribution and patience, and, again, sorry it took so ridiculously long. There were some doubts about how it's better to incorporate this feature in PyCharm, and we didn't want to expose it in master before time. 

After all the discussions we did some tweaks to the original implementation. If you're interesting I tried to [list all of them](https://github.com/JetBrains/intellij-community/commit/7534568b453d67440dc84fd8b80c81e5ad688a74) in the subsequent commit.

**Comment by jansorg** [comment]
@east825 Thank you for merging this and for the fixes applied on top!

**Pull request closed without merging**
