### PR TITLE
IDEA-139310: Find Usages reports source code usages first

### PR DESCRIPTION
**Pull request by kernc**
This builds upon 327c0facb1ed52945d2d24b3429ca456b6068416 and does what the [issue](https://youtrack.jetbrains.com/issue/IDEA-139310) asks for and people require: source code usages
(static or "dynamic") first, non-code usages (documentation) second, and generated code last..

No CLA necessary. If you agree, please apply the change in your name.

### CODE REVIEW

**Comment by klikh** [comment]
> No CLA necessary. If you agree, please apply the change in your name.

Unfortunately, it is necessary. Could you please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com?

**Comment by kernc** [comment]
Have done it. Thanks.

**Comment by klikh** [comment]
Received, thanks.

**Comment by kernc** [comment]
No problem! Anything to facilitate seeing this in the next release. :stuck_out_tongue:

**Comment by chashnikov** [comment]
Merged manually. The fix will be included into the next IDEA 16 EAP build.
Thank you for the contribution!

**Pull request closed without merging**
