### PR TITLE
IDEA-66284 ant integration - "description" attribute for "attribute" ele...

### PR DESCRIPTION
**Pull request by VISTALL**
...ment under "macrodef" not recognized

### CODE REVIEW

**Comment by ignatov** [comment]
Please update the PR.

**Comment by VISTALL** [comment]
Hello. I'm not interested in this PR anymore. Sorry

**Comment by naXa777** [comment]
there's only 1 conflicting file and it looks resolvable. @eugenezh will you please turn your eyes to it? it could be an easy win.

**Comment by amaembo** [comment]
Obsolete

**Pull request closed without merging**
