### PR TITLE
Fix PY-21146,PY-21203,PY-21145,PY-21125

### PR DESCRIPTION
**Pull request by fitermay**

### CODE REVIEW

**Comment by Elizaveta239** [comment]
@fitermay Thank you! I'll review it as soon as possible.

**Comment by Elizaveta239** [comment]
I like your changes, except for the fix of PY-21145. I always get an exception, when I try to press Ctrl+C while entering command:
`Assertion failed: Write access is allowed inside write-action only (see com.intellij.openapi.application.Application.runWriteAction())
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteAccessAllowed(ApplicationImpl.java:1231)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertWriteAccess(DocumentImpl.java:616)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:499)
	at com.jetbrains.python.console.PydevConsoleRunnerImpl$6.lambda$actionPerformed$0(PydevConsoleRunnerImpl.java:695)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:323)
	at com.jetbrains.python.console.PydevConsoleRunnerImpl$6.actionPerformed(PydevConsoleRunnerImpl.java:695)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:636)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:202)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:635)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by fitermay** [comment]
Yes, it looks like I forgot write action around it. Strange that I didn't get that exception myself.

**Comment by fitermay** [comment]
Please try now

**Comment by Elizaveta239** [comment]
Ok, I'll pass it to our QA team.

**Comment by Elizaveta239** [comment]
Thank you! Your commits are merged to master.

**Pull request closed without merging**
