### PR TITLE
Pluggable file watcher

### PR DESCRIPTION
**Pull request by dslomov**
This implements a new extension point that allows plugins to provide
their own implementation of file watchers, not requiring a different
fsnotify binary.

### CODE REVIEW

**Comment by dslomov** [comment]
Friendly ping

**Comment by trespasserw** [comment]
Busy, sorry :( Will review it by the end of next week, promise.

**Comment by trespasserw** [comment]
Just wondering - how are you going to use this?

**Comment by trespasserw** [comment]
Pushed upstream with some cosmetic changes.

**Comment by dslomov** [comment]
This thread has context: https://devnet.jetbrains.com/message/5545819#5545819

**Pull request closed without merging**
