### PR TITLE
Sync idea_default_no_spellchecker.xml

### PR DESCRIPTION
**Pull request by dahlstrom-g**
… with idea_default.xml after divergence since commit a3f7112f4fa.

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@akozlova?

**Comment by akozlova** [comment]
What does 'sync' mean? This profile is used on our internal CI, nothing else. Thanks

**Comment by dahlstrom-g** [comment]
> What does 'sync' mean?

“Sync” means “cause (a set of data or files) to remain identical in more than one location.” In this case, though, the files aren't intended to be completely identical; in commit a3f7112 idea_default_no_spellchecker.xml differs in two small ways: (1) the profile name has “no.spellchecker” appended, and (2) SpellCheckingInspection is disabled. I preserved those differences here.

> This profile is used on our internal CI, nothing else.

As of recently it's used on our internal CI as well; hence the concern about divergence here.

**Comment by dahlstrom-g** [comment]
resolved by commit 872b8dd

**Pull request closed without merging**
