### PR TITLE
Wrap call to LafManager.getInstance().getCurrentUIThemeLookAndFeel() in null check to prevent NPE during headless testing.

### PR DESCRIPTION
**Pull request by ChrisCarini**
# Summary

Wrap call to `LafManager.getInstance().getCurrentUIThemeLookAndFeel()` in null check to prevent NPE during headless testing.

# Issue

See below for details:
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/16040325332882-Calling-AboutTroubleInfoCollector-collectInfo-method-throws-NPE-in-tests-because-of-com-intellij-ide-ui-LafManager-getCurrentUIThemeLookAndFeel-is-null?page=1#community_comment_16830339751954
- https://youtrack.jetbrains.com/issue/IDEA-345108/Calling-AboutTroubleInfoCollector.collectInfo-method-throws-NPE-in-tests-because-of

### CODE REVIEW

**Comment by mfilippov** [comment]
@ChrisCarini Thank you for PR. I moved your fix into our codebase. I hope it will be available in the next EAP.

**Comment by ChrisCarini** [comment]
@mfilippov - perfect, thank you!

Shall we close this PR when it's out in the next EAP, or what's the 'standard' procedure here? Looks like most PRs get closed, is that because this is essentially a mirror repo of internal JB repo where the source is actually getting merged?

**Comment by ChrisCarini** [comment]
> @ChrisCarini Yes, I have no permission in this repository to close PR.

I see. I can close it out - just let me know when it has landed in EAP.

**Comment by ChrisCarini** [comment]
Perfect, I see this in `241.13688.18-EAP-SNAPSHOT` - thank you for upstreaming the fix! 🙏 🙇

**Pull request closed without merging**
