### PR TITLE
Fix incorrect closing streams in sanselan IOUtils

### PR DESCRIPTION
**Pull request by dplusic**

### CODE REVIEW

**Comment by klikh** [comment]
This class is deprecated and is not intended to be used. It was not removed only to keep compatibility with plugins which have not yet been updated.

**Comment by dplusic** [comment]
To keep compatibility, it must work properly.
The method, however, has bug that cannot copy streams of which size less than the size of a buffer.
So, not updated plugins won't work properly, and I'm using one of them.

**Comment by klikh** [comment]
Nope, "keeping compatibility" means "not breaking the stuff that used to work".

Maybe you could send a pull request to the plugin, to help the author in migrating to new API?

**Comment by dplusic** [comment]
The bug will "break the stuff that used to work".
This class is just "added" at 2017.3 with removing `org.apache.sanselan` package.
([change notes](https://github.com/JetBrains/intellij-sdk-docs/blob/master/reference_guide/api_changes_list.md#changes-in-intellij-platform-20173), [commit log](https://github.com/JetBrains/intellij-community/commit/e791557ca1489b02d178aa68960d645ab501e674))
I cannot find the original source of your customized `org.apache.sanselan` package, but it doesn't have the same bug. (Please refer this [source](https://github.com/apache/sanselan/blob/trunk/src/main/java/org/apache/commons/imaging/util/IoUtils.java#L172))

**Comment by klikh** [comment]
@gregsh Please have a look.

**Comment by gregsh** [comment]
@dplusic Thanks for the fix! Will see it backported.

**Pull request closed without merging**
