### PR TITLE
Add support for Log4J 2 to LoggerInitializedWithForeignClass inspection

### PR DESCRIPTION
**Pull request by MariusVolkhart**

### CODE REVIEW

**Comment by MariusVolkhart** [comment]
I was not able to run these tests locally. I can't get IDEA to compile because I can't seem to find a version of JavaFX compatible with AdoptOpenJDK 8, and IDEA doesn't compile with Java 11.

Can the tests be verified as part of a remote run? Or can you point me to a download of JavaFX that is JDK 8 compatible?

**Comment by akozlova** [comment]
You can download JetBrains [Runtime](https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime) 8 to run and compile IDEA...

**Comment by BasLeijdekkers** [comment]
Thank you, I like the structuring of the constants.

Does this pull request have a corresponding YouTrack issue? If not, could you create one? https://youtrack.jetbrains.com/issues/IDEA

Secondly, instead of creating a separate quick fix test, please add `checkQuickFixAll();` to the test method of `LoggerInitializedWithForeignClassInspectionTest` and add a `<caret>` to the test data, plus a `.after.java` file. It is nicer to have all the tests for this inspection in one place.

**Comment by MariusVolkhart** [comment]
@akozlova Thanks for the help!

@BasLeijdekkers Thanks for the feedback. The YouTrack issue is https://youtrack.jetbrains.com/issue/IDEA-240494

I've made some changes based on your comments and being able to run the `doTest()` tests. However, I'm running into problems when I try to run the `checkQuickFixAll()` verifications.

The `JBLabel myText2Label` field in `ProgressDialog` is `null`. I'm running the tests on a Mac. I'm following the directions outlined at https://github.com/JetBrains/intellij-community#running-intellij-idea

```java
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'comp' of com/intellij/util/ui/UIUtil.applyStyle must not be null

	at com.intellij.util.ui.UIUtil.$$$reportNull$$$0(UIUtil.java)
	at com.intellij.util.ui.UIUtil.applyStyle(UIUtil.java)
	at com.intellij.openapi.progress.util.ProgressDialog.initDialog(ProgressDialog.java:108)
	at com.intellij.openapi.progress.util.ProgressDialog.<init>(ProgressDialog.java:91)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$new$0(ProgressWindow.java:97)
	at com.intellij.openapi.progress.util.ProgressWindow.initializeDialog(ProgressWindow.java:118)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2240)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:100)
	at com.intellij.openapi.progress.util.PotemkinProgress.<init>(PotemkinProgress.java:40)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$13(ApplicationImpl.java:971)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:996)
	at com.intellij.openapi.application.impl.ApplicationImpl.runEdtProgressWriteAction(ApplicationImpl.java:970)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithCancellableProgressInDispatchThread(ApplicationImpl.java:960)
	at com.intellij.codeInspection.actions.CleanupInspectionUtilImpl.lambda$applyFixesNoSort$0(CleanupInspectionUtilImpl.java:39)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:211)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at com.intellij.codeInspection.actions.CleanupInspectionUtilImpl.applyFixesNoSort(CleanupInspectionUtilImpl.java:35)
	at com.intellij.codeInspection.actions.CleanupInspectionUtil.applyFixes(CleanupInspectionUtil.java:39)
	at com.intellij.codeInspection.actions.CleanupInspectionIntention.invoke(CleanupInspectionIntention.java:64)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:187)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:253)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:225)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:209)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$null$52(CodeInsightTestFixtureImpl.java:2018)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.codeWithMe.ClientId$Companion$withClientId$1.invoke(ClientId.kt:96)
	at com.intellij.codeWithMe.ClientId$Companion$withClientId$1.invoke(ClientId.kt:25)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:114)
	at com.intellij.codeWithMe.ClientId$Companion.withClientId(ClientId.kt:95)
	at com.intellij.codeWithMe.ClientId.withClientId(ClientId.kt)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:129)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:185)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:737)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.ui.UIUtil.dispatchAllInvocationEvents(UIUtil.java:1738)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$invokeIntention$53(CodeInsightTestFixtureImpl.java:2024)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.withReadOnlyFile(CodeInsightTestFixtureImpl.java:2045)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.invokeIntention(CodeInsightTestFixtureImpl.java:2014)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$launchAction$14(CodeInsightTestFixtureImpl.java:768)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:44)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.launchAction(CodeInsightTestFixtureImpl.java:768)
	at com.siyeh.ig.LightJavaInspectionTestCase.checkQuickFix(LightJavaInspectionTestCase.java:106)
	at com.siyeh.ig.LightJavaInspectionTestCase.checkQuickFixAll(LightJavaInspectionTestCase.java:113)
	at com.siyeh.ig.javadoc.MissingDeprecatedAnnotationInspectionTest.testMissingDeprecatedAnnotation(MissingDeprecatedAnnotationInspectionTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$9(UsefulTestCase.java:347)
	at com.intellij.testFramework.UsefulTestCase.lambda$invokeTestRunnable$10(UsefulTestCase.java:384)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:44)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:383)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:366)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:401)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$3.run(EdtTestUtil.kt:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:417)
```

I get this error when I run _any_ tests that call `checkQuickFixAll()`, including existing tests in the repo.

**Comment by BasLeijdekkers** [comment]
@MariusVolkhart the default vm parameters when I run a test in the IntelliJ IDEA project are:
```
-ea
-Didea.home.path=../
-Xbootclasspath/p:../out/classes/production/boot
-XX:+HeapDumpOnOutOfMemoryError
-Xmx512m
-Didea.system.path=../test-system
-Didea.config.path=../test-config
-Didea.test.group=ALL_EXCLUDE_DEFINED
-Djava.system.class.loader=com.intellij.util.lang.UrlClassLoader
-noverify
-XX:TieredStopAtLevel=1
-Djava.awt.headless=true
```
Especially the last parameter seems relevant to your problem.

**Comment by BasLeijdekkers** [comment]
I merged the changes manually, with some small changes in the test. Thank you!

**Pull request closed without merging**
