### PR TITLE
Added ability to patch python command line via Python sdk flavor

### PR DESCRIPTION
**Pull request by da1z**
Allow plugin sdk to override command line when running python tools

### CODE REVIEW

**Comment by traff** [comment]
Hi Kiryl,
thanks for the pull request. 
Could you please explain what kind of command line patching you would like to provide in a flavor?

**Comment by da1z** [comment]
Hi Dmitry,
Our interpreter uses custom arguments and need to setup the environment correctly. In some cases we need to redirect to another helper script entirely
1) For running helpers such as PYCODESTYLE, DOCSTYLE we need to setup arguments and environment
2) For generator3 we need to proxy the script
3) For PythonHelper.SYSPATH we need to proxy the script in order to get packages that are imported through custom importers (not on sys.path)

**Comment by da1z** [comment]
Hi @traff 
Any comments or suggestions on this?

**Comment by tejksat** [comment]
@da1z PyCharm team is in the process of refactoring a part of PyCharm that performs code execution (Python run configurations and around). Taking part in this work I have stumbled across `PythonSdkFlavor.commandLinePatcher()`. I have not found usages on [JetBrains Marketplace](https://plugins.jetbrains.com), but I have found this commit. Being the author of these changes do you aware of the usages of this method?

**Pull request closed without merging**
