### PR TITLE
+ added Git rebase current branch action directly from VCS log

### PR DESCRIPTION
**Pull request by dmitry-zhuravlev**
Added Git rebase current branch action directly from VCS log.
It is more convinient to do rebase directly from VCS log because user can choose some commit (point in history) and initiate rebase to it.
This is a common use case when an user do a lot of "reword" and "edit" rebases.

### CODE REVIEW

**Comment by dmitry-zhuravlev** [comment]
untitled

**Comment by klikh** [comment]
This action should be enabled only for unpushed commits (more precisely, for commits not pushed to a protected branch), like it is already done for `GitUncommitAction`.

I'm just about to push new "Reword" action, implementation of which generalizes this "enabled only for unpushed commits" stuff. I will take a look at the possibility to integrate this general interactive rebase action after that.

**Comment by dmitry-zhuravlev** [comment]
@klikh Thanks for review!

>more precisely, for commits not pushed to a protected branch

Indeed that would be good to restrict. 
Also found the following small typo to notice:
 `ParametersListUtil.COLON_LINE_PARSER` in fact it should be named `SEMICOLON_LINE_PARSER` since `;` used like a delimiter. The same applied for `ParametersListUtil.COLON_LINE_JOINER`

**Comment by klikh** [comment]
I've added the action in 197d30515085819bb440283740b77b9e935e2697 with some simplifications to the pull request, since we already have the `GitCommitEditingAction` which encapsulates the logic of preventing modification of pushed commits.

Thanks for the contribution!

**Pull request closed without merging**
