### PR TITLE
IDEA-139903 TaskManagement: Trello: Change 'number' placeholder in commit message

### PR DESCRIPTION
**Pull request by maximethebault**
https://youtrack.jetbrains.com/issue/IDEA-139903

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by maximethebault** [comment]
Not yet, I'll when I get my hands on a printer (is printing out the document absolutely needed by the way?)

**Comment by klikh** [comment]
If you already have your signature scanned, you can insert it to the document image. But the signature is necessary.

**Comment by maximethebault** [comment]
The e-mail was just sent! Let me know if there's any problem :)

**Comment by klikh** [comment]
Agreement was received. Thanks!

**Comment by east825** [comment]
@maximethebault I see no problems here. Thanks!

**Pull request merged**
