### PR TITLE
IDEA-169037 Fix Kotlin download failure.

### PR DESCRIPTION
**Pull request by waynr**

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by waynr** [comment]
@klikh done, I think

**Comment by waynr** [comment]
Actually I keep getting "Something is wrong. Please, try again later or reach out to us at ..."

**Comment by waynr** [comment]
Oh whoops, looks like it did work--I didn't realize it sent me docusign thing. Or rather it sent me one docusign thing for each time I clicked submit...I signed one of them.

**Comment by klikh** [comment]
We received the CLA, thank you.

**Comment by yole** [comment]
This is already fixed in fbd745fd341fc24771af06e8e6b9c56daab90791

**Pull request closed without merging**
