### PR TITLE
IDEA-149976 Added "Reveal in Terminal" action.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Hello.

I've decided to speed up things a bit and implement the https://youtrack.jetbrains.com/issue/IDEA-149976 feature.

The implementation was pretty straightforward except for new methods in `ToolWindow` interface, I have some doubts about them as a way of achieving the functionality required.
The idea was to be able to pass a file, selected by user, to external modules like plugins.
I've provided a default implementation of the methods in case some external code have used the interface.

If there is something that can be improved, please let me know.

### CODE REVIEW

**Comment by unlimitedsola** [comment]
And it seems JetBrains won't do things speedily 😄

**Comment by SomeoneToIgnore** [comment]
Yeah, I wish they've commented the issue at least :)

**Comment by unlimitedsola** [comment]
I'm very disappointed in JetBrains on how they deal with issues and pull requests

**Comment by traff** [comment]
Merged

**Pull request closed without merging**
