### PR TITLE
IDEA-106194 Search in File structure dialog with paste support

### PR DESCRIPTION
**Pull request by bedla**
Hi,
I have created improvement for issues https://youtrack.jetbrains.com/issue/IDEA-106194. I have not made test but if you want some please give me a hint (example test etc.) - then I will create one.
Hope you will like it.
Thx,
Ivos

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by bedla** [comment]
CLA printed, signed, scanned and sent to email...

**Comment by klikh** [comment]
CLA was received. Thank you.

**Comment by ignatov** [comment]
Thanks, manually merged.

**Pull request closed without merging**
