### PR TITLE
IDEA-189671: Refresh Editor Focus after closing split

### PR DESCRIPTION
**Pull request by lumie1337**

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by lumie1337** [comment]
I have signed the contributor license agreement now.

**Comment by Vassiliy-Kudryashov** [comment]
Thank you, but the fix you suggested is a bit tricky, I've fixed the problem in more obvious way (I believe).

**Comment by lumie1337** [comment]
the reason i fixed it this way is because there are quite a few edge cases which just get fixed by "resyncing" the state. it would obviously be better to make sure that things are always kept in sync, but that would involve a much bigger change.

**Comment by ignatov** [comment]
@lumie1337 thanks for the fix, the original issue has been fixed in master.

**Pull request closed without merging**
