### PR TITLE
[gradle] Don't mark includeBuild modules as buildSrc modules

### PR DESCRIPTION
**Pull request by fp7**
Issue: IDEA-317967

### CODE REVIEW

**Comment by nskvortsov** [comment]
I apologize for the delay
@fp7 there are some problems with the pull request (too much commits included). Would you mind cleaning it up a bit?

**Comment by fp7** [comment]
> I apologize for the delay 

No worries.

> there are some problems with the pull request (too much commits included). Would you mind cleaning it up a bit?

Yeah, sure. I rebased it.

**Comment by nskvortsov** [comment]
I took another look at the problem and the suggested solution and found it viable this time. I made a slight modification for the proposed pull request (removed the replacement, simply dropped the call to `setBuildSrcModule`) and now run it through the CI.

**Comment by fp7** [comment]
I investigated this some time ago again, too and came up with a different pull request that would solve the same problem i have in a different way. It also solves the rebuild problem if the module is a buildSrc module for real.

https://github.com/JetBrains/intellij-community/pull/2503.

**Pull request closed without merging**
