### PR TITLE
KTIJ-20330 Redundant 'inner' modifier inspection: don't warn on classes annotated with JUnit5 @Nested

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-20330

### CODE REVIEW

**Comment by akozlova** [comment]
I think, it's worth making java and kotlin inspections to be similar. In junit 5, you can write your own engines and process classes/annotations differently. Thus I'd suggest to have a configuration panel when users may add/remove annotations, see `com.siyeh.ig.memory.InnerClassMayBeStaticInspection`. Thanks

**Comment by nikitabobko** [comment]
Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix them all or share your results as a comment.

**Comment by t-kameyama** [comment]
> Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix all the warnings introduced by the inspection (in separate commit but in this PR) or share your results as a comment.

https://github.com/JetBrains/intellij-community/pull/1862#issuecomment-1016055417

**Comment by klunnii** [comment]
Can I ask you to resolve merge conflict, please?

**Comment by klunnii** [comment]
Merged. Thank you!

**Pull request closed without merging**
