### PR TITLE
fix:IDEA-128201

### PR DESCRIPTION
**Pull request by siosio**
Added the following Generate Action.
- JUnit BeforeClass and AfterClass method
- TestNg BeforeClass and AfterClass method

### CODE REVIEW

**Comment by ignatov** [comment]
@siosio, please rebase the PR, cc @akozlova.

**Comment by naXa777** [comment]
hey @siosio
this PR is waiting for you.

**Comment by siosio** [comment]
sorry for the late response.
fix rebase and conflicts.

**Comment by naXa777** [comment]
@siosio 
is this issue [IDEA-128201](https://youtrack.jetbrains.com/issue/IDEA-128201) still reproducible? there are chances it's indirectly fixed somewhere between 2015 and 2019...
    1. if no ->
        * just close this PR.
    2. if yes ->
        * can you please update the PR so it's ready to be merged?

**Comment by siosio** [comment]
@naXa777 No2(It can be reproduced.)
I will check if it can be fixed in 2019. If can't fix it on 2019, close PR.

**Comment by siosio** [comment]
rebase and fix conflict.

**Comment by naXa777** [comment]
@siosio thank you!
@akozlova please turn your eyes to this PR.

**Comment by akozlova** [comment]
Merged manually with some small changes. Thanks

**Pull request closed without merging**
