### PR TITLE
Extract Fields From Continuation This Pointer as Local Variables

### PR DESCRIPTION
**Pull request by alonalbert**
https://youtrack.jetbrains.com/issue/KT-54426/Local-Variables-Not-Shown-in-Debugger-Inside-a-Suspend-Lambda

### CODE REVIEW

**Review by madsager — COMMENTED** [review]
This does not appear to work in the (likely common) case where developers are using kotlinx.coroutines. So, I think we have to dive deeper (see individual comments).

Also, let's make sure that we add some tests for this. I think the best place for that is `KotlinVariablePrintingTestGenerated` which is auto-generated from files in `plugins/kotlin/jvm-debugger/test/testData/variables`. So, we should create tests along the lines of:

```
// ATTACH_LIBRARY: coroutines
// SHOW_KOTLIN_VARIABLES

import forTests.builder

suspend fun bar() {
    val x = "Hello"
    barLambdaRunner {
        //Breakpoint!
        println(x)
    }
}

suspend fun barLambdaRunner(f: suspend () -> Unit) = f()

fun main() {
    builder {
        bar()
    }
}
```

However, we should also attempt to update the tests so that we can use kotlinx-coroutines in the tests to make sure that we cover all the typical cases.

**Comment by madsager** [comment]
@yanex @ilmirus looping you in as you might know more about how this is supposed to work than I do. :)

**Comment by madsager** [comment]
I wonder if we should just add the option of extracting the dispatch receiver from the stack frame proxy. The `this` object is confusing as it can be either an extension receiver or a dispatch receiver when looking at coroutines. The following commit is a hacked up prototype of that which allows us to extract and show the captures in the cases where `thisObject` returns the extension receiver:

https://github.com/madsager/intellij-community/commit/cba64913c2cbea198af86c48d3f64eac1103f16b

**Comment by alonalbert** [comment]
I'm closing this PR because it's not the right approach anyway, and my local git clone got messed up.

I forked @madsager from above and added tests.

I think we should move the conversation to the bug instead of here.

**Pull request closed without merging**
