### PR TITLE
FIR UAST: test updates (annotation on destructuring declaration)

### PR DESCRIPTION
**Pull request by jsjeon**
This is simple test data updates for [KOTLIN-CR-211](https://kotlin.jetbrains.space/p/kotlin/reviews/211/), along with a minor fix for identifer test.

### CODE REVIEW

**Comment by jsjeon** [comment]
KOTLIN-CR-211 was merged, and this will be needed to not break the build in this repo/branch.

**Comment by darthorimar** [comment]
Merged, thanks!

**Comment by jsjeon** [comment]
Hm, I'm not seeing these commits in kt-212-master. @fedochet, could you take a look at these?

**Comment by jsjeon** [comment]
> @jsjeon looking into it, thanks!

Now I see them, thank you!

**Pull request closed without merging**
