### PR TITLE
Minor pycharm fixes

### PR DESCRIPTION
**Pull request by fitermay**
Details:
One issue is refreshing the sdk in details dialog invokes PySdkUpdater, which in turn invalidates the modificator. the dialog tries to then use the invated modificator causing an assertion error and an NPE.

Issue two is framewok updater waits for process output on UI thread causing a major lockup

### CODE REVIEW

**Comment by fitermay** [comment]
@vlasovskikh ping

**Comment by vlasovskikh** [comment]
@fitermay Thanks for your PR. We've already [fixed](https://youtrack.jetbrains.com/issue/PY-19170) the first issue with NPE. I'll get back to this PR in a few days, sorry for the delay.

**Comment by fitermay** [comment]
Hi,
I've seen the fix to the NPE. I'm pretty sure it leaves an issue of not picking up further changes in the dialog after the first Sdk refresh. That is if user refreshes Sdk then makes other changes those changes won't be picked up.

**Comment by vlasovskikh** [comment]
@fitermay Please rebase your PR on top of the master branch and I'll merge it.

**Comment by fitermay** [comment]
@vlasovskikh Done

**Comment by vlasovskikh** [comment]
@fitermay Thank you for the PR.

**Pull request merged**
