### PR TITLE
PY-56361

### PR DESCRIPTION
**Pull request by guoci**
Fix for PY-56361
https://youtrack.jetbrains.com/issue/PY-56361/pandas-Series-iteritems-in-pydevdutilspy-FutureWarning

### CODE REVIEW

**Comment by lancelote** [comment]
@guoci Thank you for the fix. Could you elaborate on why you use `iloc`?

**Comment by guoci** [comment]
@lancelote A warning will be triggered with the following code on the python console.
image


```
import pandas as pd, numpy as np
pd.Series(range(3), index=np.arange(1,4))
```
``` FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  s = s[:max_items]```

**Comment by kierke-gaard** [comment]
same here. almost for every pandas command, I'll get the warning in the pycharm interpreter. 

/mnt/c/Program Files/JetBrains/PyCharm 2021.3.2/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_utils.py:606: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in s.iteritems():

**Comment by lancelote** [comment]
Thank you for the contribution. Merged in the monorepo. The fix will be available in PyCharm 2022.3.1.

**Pull request closed without merging**
