### PR TITLE
Apply hard-coded contracts to assume methods

### PR DESCRIPTION
**Pull request by dahlstrom-g**
… just like existing contracts for assert methods.

https://youtrack.jetbrains.com/issue/IDEA-158732

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please check your inbox: I've just send there the CLA to sign. Thanks.

**Comment by dahlstrom-g** [comment]
This contribution is work for hire at Google; the company has a contributor license agreement with JetBrains. I can provide contacts for verification if you like.

You can also see the account I'm using belongs to the Google organization on GitHub (github.com/google).

**Comment by klikh** [comment]
We're not aware of such agreement between Google and JetBrains. There were some plans about the CLA, but AFAIK it was not signed yet. So please provide contacts to verify this.

**Comment by dahlstrom-g** [comment]
Carol Lin <carollin@google.com> can verify Google's CLA with JetBrains.

**Comment by carollin-g** [comment]
Hi @klikh, we've signed a corporate CLA in December of 2009. Please check with your OS contribution office or email me for the actual agreement.

**Comment by klikh** [comment]
Everything is handled with the CLA now. Thanks. We'll review the patch soon.

**Comment by donnerpeter** [comment]
Pushed to master, thanks for the contribution!

**Pull request merged**
