### PR TITLE
Fix kotlin.jvm-run-configurations module

### PR DESCRIPTION
**Pull request by punzki**

### CODE REVIEW

**Comment by punzki** [comment]
@fedochet Please have a look, build for plugin is broken

**Comment by vladimirdolzhenko** [comment]
Sorry, could you please provide the reason behind your change ?

**Comment by punzki** [comment]
> Sorry, could you please provide the reason behind your change ?

@vladimirdolzhenko The Kotlin plugin doesn't build without this change. I already talked to @fedochet on Slack about this.

**Comment by fedochet** [comment]
Closing this PR since the required changes are already in this repo: c0ae8756d6b9ddc95dbbbbba27caeaaff76c1d59 and a5ef8bdd3d9dcfc76739f55693975173d32bd93c

Thanks @punzki for bringing it up!

**Pull request closed without merging**
