### PR TITLE
Add PYCHARM_DISPLAY_HOST env var for remote access

### PR DESCRIPTION
**Pull request by adampl**
Enables displaying matplotlib charts in SciView from Docker-based and remote interpreters.

See:
https://youtrack.jetbrains.com/issue/PY-32668/Cannot-view-plots-from-remote-python-interpreter-natively-in-PyCharm-SciView
https://youtrack.jetbrains.com/issue/PY-33558/Matplotlib-in-Docker-container-fails

Workaround described here:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000017759/comments/7654144737170

### CODE REVIEW

**Comment by adampl** [comment]
The port forwarding trick will be necessary as long as the following ticket isn't resolved:
https://youtrack.jetbrains.com/issue/PY-27489/SciView-configure-listener-interface

**Comment by adampl** [comment]
@Elizaveta239 Can you merge it?

**Comment by Elizaveta239** [comment]
Hi @adampl! Yes, sure, but a bit later (in a couple of weeks), together with fixing compatibility for 2022.3 release

**Comment by adampl** [comment]
@Elizaveta239 Looks like it's been pulled into `master`, but not merged as a PR. What's the next step?

**Comment by Elizaveta239** [comment]
Hi! Yes, this repository is actually a mirror of our internal repository, so we merge pull requests manually. Thank you very much for your contribution!

**Pull request closed without merging**
