### PR TITLE
Java inspection for allocation of array with negative size

### PR DESCRIPTION
**Pull request by bedla**
Hi,
please see details in issue https://youtrack.jetbrains.com/issue/IDEA-254545 .
Thx,
Ivos

### CODE REVIEW

**Comment by amaembo** [comment]
Thank you for your pull-request. I will reuse your tests but in general, this should be a part of data-flow analysis. I will implement it by myself.

**Comment by bedla** [comment]
ahh, I see. I am looking forward to data-flow analysis solution - to learn something new :)

**Comment by amaembo** [comment]
See 5e6932f3b5f93d8e331919bb9ec9be64206e1311.

**Comment by bedla** [comment]
cool, thx for sharing :)

**Pull request closed without merging**
