### PR TITLE
Decompiler name shadowing resolution

### PR DESCRIPTION
**Pull request by apixandru**
'package1.ClassA.ClassB' is falsely identified as 'package1.ClassA' by any class that is in another package other than package1 if that package also contains a class named 'ClassA'.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by apixandru** [comment]
Sure, I sent the email a couple of hours ago with the subject 'CLA apixandru'

**Comment by klikh** [comment]
The CLA was received. Thanks.

**Comment by trespasserw** [comment]
I have rewritten the test and pushed the changes upstream.
Thanks!

**Pull request closed without merging**
