### PR TITLE
[IDEA-171546] Allow Merging Git tags

### PR DESCRIPTION
**Pull request by DevDengChao**
Add MergeAction into TagActions group.

example

The original ticket: https://youtrack.jetbrains.com/issue/IDEA-171546/Allow-Merging-Git-tags

### CODE REVIEW

**Comment by DevDengChao** [comment]
Should we add a Separator between merge and delete tag action ?

**Comment by DevDengChao** [comment]
May I request for merge this PR instead of close it and re-commit those changes with that bot?

Or is there any public documents for why the bot need to do it or the team to treat PR that way ?

**Comment by DevDengChao** [comment]
@dmitriysmirnovjb Hello ?

**Comment by juliabeliaeva** [comment]
> May I request for merge this PR instead of close it and re-commit those changes with [intellij-monorepo-bot](https://github.com/intellij-monorepo-bot)?
> 
> Or is there any public documents for why the bot need to do it or the team to treat PR that way ?
> 
> I think the `Merged Pull Request` do make sense to contributors.

No, direct merges are not possible, sorry. PRs are merged to our internal repository first, which is then synchronised with GitHub.

**Comment by juliabeliaeva** [comment]
@DevDengChao thank you for the PR. Everything looks good, going to merge the changes manually.

**Pull request closed without merging**
