### PR TITLE
IDEA-306015 disable the annoying error icon that keeps flashing the same error every twenty minutes

### PR DESCRIPTION
**Pull request by aSemy**
[IDEA-306015](https://youtrack.jetbrains.com/issue/IDEA-306015)

The icon does not serve a useful purpose. It has never alerted me to something actionable. It's just plain annoying.

### CODE REVIEW

**Comment by yole** [comment]
If the icon does not serve a useful purpose for you personally, you can disable it via the system properties on your machine. It does serve a very useful purpose for IDE developers and many EAP users.

**Comment by aSemy** [comment]
> you can disable it via the system properties on your machine.

This is not possible

**Comment by yole** [comment]
The specific options for that are discussed in the linked YouTrack issue. In any case, removing the icon entirely is not an acceptable solution for the problems you're experiencing.

**Comment by aSemy** [comment]
hey @yole, those options don't work

image

**Comment by aSemy** [comment]
The option still doesn't work, I'm constantly pinged by this annoying icon

image

**Comment by yole** [comment]
I'm sorry for the inconveniences you're experiencing, but they are still not a valid reason to accept your PR.

**Pull request closed without merging**
