### PR TITLE
[maven] IDEA-296303 respect preview property and parameter

### PR DESCRIPTION
**Pull request by beatngu13**
Fixes [IDEA-296303](https://youtrack.jetbrains.com/issue/IDEA-296303).

### CODE REVIEW

**Comment by beatngu13** [comment]
[JDK 21](https://openjdk.org/projects/jdk/21/) is just around the corner, including several JEPs as preview features (e.g. [String templates](https://openjdk.org/jeps/430)). IntelliJ/Maven users would benefit from this PR, since the preview property and parameter are respected.

Is there a chance to move forward with this PR?

**Comment by beatngu13** [comment]
Hey @zulkar,

almost a year has passed, is there a chance to move forward with this PR?

**Comment by nskvortsov** [comment]
@beatngu13 thank you for the contribution. And separately, thank you for providing updated tests! Will run the pull request through our CI soon.

**Comment by nskvortsov** [comment]
Merged to master.
I apologize for this pull request being stuck for a crazy long time. Thank you for your patience and a solid contribution!

**Pull request closed without merging**
