### PR TITLE
DocumentationComponent: Added Base64 image support

### PR DESCRIPTION
**Pull request by markusmo3**
This adds Base64 image support to the DocumentationComponent via data uris.

### Example
Put this into Javadoc:
```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```
Source: https://en.wikipedia.org/wiki/Data_URI_scheme

### Notes
* I tried using the ImageView/MyScalingImageView but without luck, it just doesn't support anything other than an URL in the `src` attribute.
* I only implemented support for the src, width and height attribute while ImageView also has support for attributes like `hspace`, `vspace`, `border`...
* I made some inner classes from anonymous ones, but didn't change the logic of them. If that is not wanted i could revert those changes.
* ImageIO.read is used, so this implementation only supports png, jpg and gif. Sadly no svg.

Certain competitors are able to show base64 encoded images in JavaDoc. So i think IntelliJ should also be able. At work we use that to display the icons behind String constants in the JavaDoc.

Also this fixes the following: https://youtrack.jetbrains.com/issue/IDEA-104317

### CODE REVIEW

**Comment by JB-Dmitry** [comment]
Hello, Markus,
Thanks for your contribution. Could you please fix the following problems I've found:
* If only width or height is specified for the image, the other value should be scaled accordingly
* You're setting a default border for the image, this seems to be different from the default logic for other image types. Can the default be set to zero?
* I believe, MyBufferedImageView.viewToModel should behave exactly like MyIconView.viewToModel - points closer to the left image border should correspond to start offset, and vice versa.

**Comment by markusmo3** [comment]
Hello Dmitry,

I tried to keep the logic for normal images by looking at what the swing ImageView does and copying that, but i will work on your notes in the coming days.

**Comment by markusmo3** [comment]
Hello again @JB-Dmitry.
I implemented the width/height thing and also set the default border size to 0 as you requested. I does behave different to normal images though... Guess the swing ImageView does something strange...
idea_base64_img_support

The Source for this Test:
```java
/**
 * <h2>Normal images</h2>
 * <img src="https://via.placeholder.com/150"/>
 * <img width="50" src="https://via.placeholder.com/150"/>
 * <img height="50" src="https://via.placeholder.com/150"/>
 * test
 * <img height="50" align="middle" src="https://via.placeholder.com/150"/>
 *
 * <h2>Base64</h2>
 * <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWBAMAAADOL2zRAAAAG1BMVEXMzMyWlpaqqqq3t7fFxcW+vr6xsbGjo6OcnJyLKnDGAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABAElEQVRoge3SMW+DMBiE4YsxJqMJtHOTITPeOsLQnaodGImEUMZEkZhRUqn92f0MaTubtfeMh/QGHANEREREREREREREtIJJ0xbH299kp8l8FaGtLdTQ19HjofxZlJ0m1+eBKZcikd9PWtXC5DoDotRO04B9YOvFIXmXLy2jEbiqE6Df7DTleA5socLqvEFVxtJyrpZFWz/pHM2CVte0lS8g2eDe6prOyqPglhzROL+Xye4tmT4WvRcQ2/m81p+/rdguOi8Hc5L/8Qk4vhZzy08DduGt9eVQyP2qoTM1zi0/uf4hvBWf5c77e69Gf798y08L7j0RERERERERERH9P99ZpSVRivB/rgAAAABJRU5ErkJggg=="/>
 * <img width="50" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWBAMAAADOL2zRAAAAG1BMVEXMzMyWlpaqqqq3t7fFxcW+vr6xsbGjo6OcnJyLKnDGAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABAElEQVRoge3SMW+DMBiE4YsxJqMJtHOTITPeOsLQnaodGImEUMZEkZhRUqn92f0MaTubtfeMh/QGHANEREREREREREREtIJJ0xbH299kp8l8FaGtLdTQ19HjofxZlJ0m1+eBKZcikd9PWtXC5DoDotRO04B9YOvFIXmXLy2jEbiqE6Df7DTleA5socLqvEFVxtJyrpZFWz/pHM2CVte0lS8g2eDe6prOyqPglhzROL+Xye4tmT4WvRcQ2/m81p+/rdguOi8Hc5L/8Qk4vhZzy08DduGt9eVQyP2qoTM1zi0/uf4hvBWf5c77e69Gf798y08L7j0RERERERERERH9P99ZpSVRivB/rgAAAABJRU5ErkJggg=="/>
 * <img height="50" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWBAMAAADOL2zRAAAAG1BMVEXMzMyWlpaqqqq3t7fFxcW+vr6xsbGjo6OcnJyLKnDGAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABAElEQVRoge3SMW+DMBiE4YsxJqMJtHOTITPeOsLQnaodGImEUMZEkZhRUqn92f0MaTubtfeMh/QGHANEREREREREREREtIJJ0xbH299kp8l8FaGtLdTQ19HjofxZlJ0m1+eBKZcikd9PWtXC5DoDotRO04B9YOvFIXmXLy2jEbiqE6Df7DTleA5socLqvEFVxtJyrpZFWz/pHM2CVte0lS8g2eDe6prOyqPglhzROL+Xye4tmT4WvRcQ2/m81p+/rdguOi8Hc5L/8Qk4vhZzy08DduGt9eVQyP2qoTM1zi0/uf4hvBWf5c77e69Gf798y08L7j0RERERERERERH9P99ZpSVRivB/rgAAAABJRU5ErkJggg=="/>
 * test
 * <img height="50" align="middle" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAACWBAMAAADOL2zRAAAAG1BMVEXMzMyWlpaqqqq3t7fFxcW+vr6xsbGjo6OcnJyLKnDGAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABAElEQVRoge3SMW+DMBiE4YsxJqMJtHOTITPeOsLQnaodGImEUMZEkZhRUqn92f0MaTubtfeMh/QGHANEREREREREREREtIJJ0xbH299kp8l8FaGtLdTQ19HjofxZlJ0m1+eBKZcikd9PWtXC5DoDotRO04B9YOvFIXmXLy2jEbiqE6Df7DTleA5socLqvEFVxtJyrpZFWz/pHM2CVte0lS8g2eDe6prOyqPglhzROL+Xye4tmT4WvRcQ2/m81p+/rdguOi8Hc5L/8Qk4vhZzy08DduGt9eVQyP2qoTM1zi0/uf4hvBWf5c77e69Gf798y08L7j0RERERERERERH9P99ZpSVRivB/rgAAAABJRU5ErkJggg=="/>
 *
 * <h2>Other Heading</h2>
 * Test123
 */
```

I also took a look at the viewToModel method again and why it is different from the swing.ImageView one. I found the swing.IconView, which matches the MyIconView.viewToModel method again.

I'm not sure what version of the method to take, but i went with the ImageView one, as we are displaying a BufferedImage and not just icons. Let me know if that is okay with you.

**Comment by JB-Dmitry** [comment]
Hello Markus,

Thanks for the updated fix - looks better to me.
As for the image scaling logic in ImageView - it had a bug, which is fixed in JDK 12 (https://bugs.openjdk.java.net/browse/JDK-8208638) and JetBrains Runtime (https://youtrack.jetbrains.com/issue/JBR-588). You've probably used an older JDK version to test.

I see now why you've chosen that particular 'viewToModel' implementation - ImageView has the same one (didn't look at it previously). IMHO, the one in IconView is better, as e.g. a mouse click near the right edge of the image will position the caret at the right edge. But let's leave it as in your implementation, for consistency.

I've pushed your change, and also moved the new logic to JBHtmlEditorKit.

**Pull request closed without merging**
