### PR TITLE
Added building python debugger binaries for 2.6

### PR DESCRIPTION
**Pull request by da1z**
related to this issue https://youtrack.jetbrains.com/issue/PY-19216

### CODE REVIEW

**Comment by fitermay** [comment]
@Elizaveta239 I've rebased onto master and cleaned this up. The change will not introduce any additional dependencies on your side. Python 2.6 binaries are built against the same MS SDK as Python 2.7 binaries.

**Comment by vlasovskikh** [comment]
@da1z @fitermay Thanks for your pull request. Unfortunately, we won't include the debugger binaries for Python 2.6 since we consider it obsolete. Python 2.6 reached its official [end of life](https://docs.python.org/devguide/index.html#status-of-python-branches) on 2013-10-29 and in future versions of PyCharm we will drop support for it. If having compiled Cython extensions for Python 2.6 is critical for you, please consider distributing them separately from PyCharm. We could update our language check when looking for Cython extensions so PyCharm will try to load them for 2.6 from `sys.path`.

The related ticket in the issue tracker: https://youtrack.jetbrains.com/issue/PY-19215

**Comment by Elizaveta239** [comment]
@da1z @fitermay Thank you for the pull request!

**Comment by fitermay** [comment]
@Elizaveta239 Thanks for taking this. It's very important for us.

**Pull request closed without merging**
