### PR TITLE
IDEA-192953 Fix replace switch with if on primitive wrapper uses equals

### PR DESCRIPTION
**Pull request by goto1134**

### CODE REVIEW

**Comment by ignatov** [comment]
cc @BasLeijdekkers

**Comment by BasLeijdekkers** [comment]
Thanks for you contribution! Does this fix a YouTrack issue?

**Comment by goto1134** [comment]
Yes, it does. 
There are tests for replacement with Character and Integer classes.

**Comment by BasLeijdekkers** [comment]
Sorry, I missed the YouTrack ID here. Applied manually to Master, thanks!

**Pull request closed without merging**
