### PR TITLE
IDEA-131162 Detect recursion in Java call hierarchy

### PR DESCRIPTION
**Pull request by alshain**
Fixes IDEA-131162, IDEA-144116, IDEA-52371
https://youtrack.jetbrains.com/issue/IDEA-131162

### CODE REVIEW

**Comment by cdracm** [comment]
pushed, thanks

**Comment by joshgold22** [comment]
would you consider posting a screenshot of the fix?

**Comment by joshgold22** [comment]
(apologies, deleted last comment posted to the wrong ticket)

**Comment by alshain** [comment]
@cdracm Great, thanks!

**Pull request closed without merging**
