### PR TITLE
Add support for Kotlin assignment plugin

### PR DESCRIPTION
**Pull request by asodja**

### CODE REVIEW

**Comment by asodja** [comment]
Also note: to check annotations for scripts, I had to add additional dependencies to `kotlin.compiler-plugins.assignment.common` [here](https://github.com/JetBrains/intellij-community/blob/70c76239b5be74c6f6b34087316e57cf99d25ca8/plugins/kotlin/compiler-plugins/assignment/common/kotlin.compiler-plugins.assignment.common.iml#L21-L22). Please validate if that is ok.

Also I added a reference to a assignment plugin on all places where sam-with-receiver is added, please validate also that.

**Comment by darthorimar** [comment]
I've changed assignee of the PR to @yanex. Yan worked on existing K1 plugins support in the IDE

**Comment by asodja** [comment]
@yanex Since assignment compiler plugin will be in Kotlin 1.8.0, could this get in to the IntelliJ that will support Kotlin 1.8.0?

**Comment by yanex** [comment]
The commits arrived in `master` and `223`branches several months ago, I hope you have already found them.
Sorry for keeping the PR open.

Just in case, here are the commits in `223` branch:
https://github.com/JetBrains/intellij-community/commit/0215ddf2887dfc1d45b836738e406a2db21640fe
https://github.com/JetBrains/intellij-community/commit/5bba276dfaa578305709fb6d026bc42019f5ae16
https://github.com/JetBrains/intellij-community/commit/9abb72f3189d309e87484be95a2e6c06114e330a
https://github.com/JetBrains/intellij-community/commit/5a5af8d9d8ec5d0a0c8ff9f29c05a615b41a8ef1

And here are they in `master`:
https://github.com/JetBrains/intellij-community/commit/c39c23e4c8f6877f684b74baa1ea8456f646d4d7
https://github.com/JetBrains/intellij-community/commit/db5b90c8a59260d483693df9f2bb92322a38d5ad
https://github.com/JetBrains/intellij-community/commit/adafc71d1c3cf3ff43da01dccacfe7320b475098
https://github.com/JetBrains/intellij-community/commit/543be6f56f45511a26a0fbf072914f994ea42a28

Thank you for your contribution!

**Pull request closed without merging**
