### PR TITLE
[IDEA-37227] Add new "Boolean expression may be factorized" inspection

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
[Creates a new inspection that factorizes boolean expression when possible](https://youtrack.jetbrains.com/issue/IDEA-37227):

`isValid && isFound || isValid && isActive`

becomes:

`isValid && (isFound || isActive)`

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
@BasLeijdekkers,

OK so I should not delete and recreate a branch too... So I have squashed your requests and I think I will implement your improvements (handling numeric and other operators) in a further ticket.

**Comment by BasLeijdekkers** [comment]
Hi @Fabrice-TIERCELIN ,
I forgot to ask you the most important question: Have you signed a contributor agreement?
https://www.jetbrains.com/agreements/cla/

**Comment by Fabrice-TIERCELIN** [comment]
Hi,

It's not working 😢

_Something is wrong. Please, try again later or reach out to us via_

**Comment by Fabrice-TIERCELIN** [comment]
✔️Done!

It didn't work on Firefox but on Chrome

**Comment by BasLeijdekkers** [comment]
Hi @Fabrice-TIERCELIN 
Your pull request is now part of IntelliJ IDEA: https://github.com/JetBrains/intellij-community/commit/6d0b73b55c1b7eda3f7d2b31b510d88b8c6c4f40
Unfortunately I may have done something wrong when merging this, because I see now it is not showing you as the author in Git. Sorry! I will make sure this does not happen again.

**Comment by Fabrice-TIERCELIN** [comment]
No matter @BasLeijdekkers, it's OK. And my name is displayed as author. We will check it for the next time.

Each time we implemented a cleanup in the Eclipse project, we used to do a dogfooding session. We created another ticket that cleans all the code of the IDE using the new feature:

1. To improve the code of the IDE,
2. To test the new cleanup,
3. To show to the user we trust our code.

It should be done:

1. At the start of an iteration
2. When no bug is open

Do you do this?

**Comment by BasLeijdekkers** [comment]
We always try to run new inspections over our code, to give it a real world test, but only apply the fix if we see the value in the fix. In this case there are no issues to be found in IntelliJ IDEA Community code as far as I can tell.

**Pull request closed without merging**
