### PR TITLE
New function "regularExpression" for livetemplates.

### PR DESCRIPTION
**Pull request by michaelsiepmann**
Sometimes it is usefull to change a value. In my special example, I have a template for a unit-test and want to insert the classname of the class to test. Normally this name is the current class without the suffix "Test". This suffix can be removed with a regular expression.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by michaelsiepmann** [comment]
Now, I've made this up.

**Comment by klikh** [comment]
We've received the CLA, thanks.

**Comment by michaelsiepmann** [comment]
Sorry, i've forgotten the LangExtensions.xml :-)

**Comment by donnerpeter** [comment]
Seems to address https://youtrack.jetbrains.com/issue/IDEA-146121, thanks!

**Comment by donnerpeter** [comment]
Merged manually to master, thanks!

**Pull request closed without merging**
