### PR TITLE
[Fernflower] Refactored IIdentifierRenamer to be more flexible.

### PR DESCRIPTION
**Pull request by ccarpenter04**
I went ahead and refactored the IIdentifierRenamer class and added some basic documentation to it. I also separated the default implementation of it into a separate class called DefaultIIdentifierRenamer and left the ConverterHelper class in place to store static methods that are useful and related to the renaming process. Classes with names differing only in case are also now renamed by default since you can't properly extract them on windows without them overwriting each other. In addition, I made it so that getNextClassName has a new argument of int accessFlags which I used to change the default class prefix from "class_" to "interface_", "enum_", and "annotation_" if appropriate. By doing that it's now easier to find what you're looking for at a glance.

### CODE REVIEW

**Comment by nicity** [comment]
Hi,
Thank you for your pull requests!
What about new tests and testing your changes?

**Comment by ccarpenter04** [comment]
I tested it in a variety of situations on several large projects to verify it works correctly, however I'm not familiar with how you guys do unit testing because of the nature of the project.

I forgot to mention it before but I've signed the CLA previously and had several similar pull requests accepted. The difficulties that I see with unit testing something like this is that is has to do with renaming and the default renamer has rather defined guidelines that would make unit testing difficult.

**Comment by ccarpenter04** [comment]
I've been working on fixing the renaming system which has long been broken and once the two pulls requests that I've submitted today are accepted there is only one more major bug in the renaming system that I'm aware of and likely a few smaller bugs that I won't be able to identify until these changes are pushed (including the fix for the remaining bug that is well documented on the issue tracker).

**Comment by nicity** [comment]
Tests are needed to avoid regressions in the future

**Comment by ccarpenter04** [comment]
@nicity Is there any documentation on how Fernflowers test system works? I know it doesn't function with standard unit tests. I'll attempt to write some tests for it but due to the nature of renaming and the fact that custom implementations of IIdentifierRenamer can be provided I'm thinking it'll be rather difficult to make reliable tests.

**Comment by ccarpenter04** [comment]
I'm going to close this pull request because I accidentally deleted the branch it was being pulled from and because of that I can't easily add on to this. I'll make a new pull request once I've made some additional tweaks and came up with some reliable tests.

**Comment by trespasserw** [comment]
@ccarpenter04 pretty standard JUnit tests (not many of them, unfortunately). See `plugins/java-decompiler/engine/build.xml` and `plugins/java-decompiler/engine/test/*` for the reference.

**Comment by ccarpenter04** [comment]
@trespasserw Oh okay, now I understand how you guys are handling them. The .dec files confused me until I realized how you guys were generating them to begin with. I'll try to have the unit tests written for this sometime this week.

**Pull request closed without merging**
