### PR TITLE
Backport KeyFMap changes

### PR DESCRIPTION
**Pull request by bashor**

### CODE REVIEW

**Comment by bashor** [comment]
@chashnikov please take a look

**Comment by chashnikov** [comment]
I'm not sure about backporting changes in interning, @donnerpeter what do you think?

**Comment by nicity** [comment]
I am against, performance implications of first commit isn't yet known.

**Comment by bashor** [comment]
Well, I excluded changes in `UserDataInterner`.

**Comment by nicity** [comment]
What about breaking API ?
Please provide reasons why we should do the backport in 141

**Comment by bashor** [comment]
>What about breaking API ?

Mainly it covers internal things and which (I think) doesn't have many usages.

I don't know your policies about changes like this. 

> Please provide reasons why we should do the backport in 141

I did these changes for Kotlin and I'd like to backport them if it possible.

**Comment by nicity** [comment]
In 141 we are in end of regular updates of IntelliJ Idea 14.1.X and any noncritical thing backported needs reasonable justification

**Comment by bashor** [comment]
Actually this PR didn't rename anything in current public API (`ArrayBackedFMap#getKeys` added and renamed during this PR).
But it added a method to `KeyFMap`, is it OK?

**Comment by nicity** [comment]
Adding method is ok.

**Comment by bashor** [comment]
So, can you merge it?

**Comment by nicity** [comment]
Let's backport If we don't change / decrease existing API

**Comment by bashor** [comment]
Well, could anybody merge it?

//cc @nicity @chashnikov

**Comment by nicity** [comment]
I backported your changes to 141 manually, please review

**Comment by bashor** [comment]
I see, thanks a lot!

**Pull request closed without merging**
