### PR TITLE
 Created configurable group for tool window context menu

### PR DESCRIPTION
**Pull request by olegstepanov**

### CODE REVIEW

**Comment by olegstepanov** [comment]
Done that

**Comment by klikh** [comment]
Thanks! @Vassiliy-Kudryashov could you please take a look?

**Comment by klikh** [comment]
And again, no "Merge remote-tracking branch" commits please ;)

**Comment by olegstepanov** [comment]
@klikh I would just make this PR obsolete. I have the new one: https://github.com/JetBrains/intellij-community/pull/861 with more comprehensive work.

**Pull request closed without merging**
