### PR TITLE
IDEA-90507 Close tabs to the right

### PR DESCRIPTION
**Pull request by vvv1559**

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please specify your real name (preferrably in commit data as well) and I'll send you an e-mail with the CLA to sign. Thanks.

**Comment by vvv1559** [comment]
No, I don't. I specified the real name in the GitHub profile.

**Comment by klikh** [comment]
Please check your inbox: I've just send there the CLA to sign. Thanks.

**Comment by vvv1559** [comment]
Completed.

**Comment by klikh** [comment]
Received, thanks.

**Comment by vvv1559** [comment]
Thanks you.

**Comment by ignatov** [comment]
@vvv1559 please update the RP if you're still interested in.
There's a plugin for that – https://github.com/tom-power/close-tab-left-right.
cc @Vassiliy-Kudryashov

**Comment by Vassiliy-Kudryashov** [comment]
@vvv1559 Actually you shouldn't operate window.getSelectedEditor() because with right-click you get context menu for 'context' file and not 'selected' file. Anyway, thank you, the issue IDEA-90507 seems to be fixed!

**Pull request closed without merging**
