### PR TITLE
[EE-IR] Support mutations by evaluator fragments

### PR DESCRIPTION
**Pull request by kandersen**
~~!!! Dependent on #1802 and JetBrains/kotlin#4647~~ !!!

- Add the new lowering to support this to the compiler invocation.

### CODE REVIEW

**Comment by kandersen** [comment]
Compiler-side changes are in.

**Comment by kandersen** [comment]
Rebased on kt-212-master!

**Comment by nikita-nazarov** [comment]
Thanks, merged! e668f9fb3500b7d33ab67541e95bf3d564cc06df

**Comment by kandersen** [comment]
Great, thank you!

**Pull request closed without merging**
