### PR TITLE
No need to scan scope for global inspection

### PR DESCRIPTION
**Pull request by g7r**

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by batya239** [comment]
Your case is running "Inspect Code..." action with an empty inspection profile?

**Comment by g7r** [comment]
@batya239, no, my case is "Run inspection by name". I made an inspection that helps me to perform sophisticated refactoring. It is designed to be executed on a whole project at once.

**Comment by g7r** [comment]
@klikh, no I haven't. Will do it shortly.

**Comment by g7r** [comment]
@klikh Done!

**Comment by klikh** [comment]
We've received the CLA. Thanks.

**Pull request merged**
