### PR TITLE
Remove final keyword from ToolWindowHeadlessManagerImpl

### PR DESCRIPTION
**Pull request by dahlstrom-g**
This was added incidentally by commit 983b3e7
breaking test doubles for the class.

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@develar

See related #1226 and #1267.

**Comment by dahlstrom-g** [comment]
@develar?

**Comment by develar** [comment]
Why do you need to mock ToolWindowHeadlessManagerImpl? Maybe it possible to modify class itself to avoid mocking? Or even simply fix some platform code to avoid usage of tool window manager?

**Comment by dahlstrom-g** [comment]
I'm not the author and don't have answers to your questions, but you can refer to [commit 86f530b](https://android.googlesource.com/platform/tools/adt/idea/+/86f530b) and send a fix there instead if you prefer. To me, as in previous instances, it seems simpler to avoid adding the final modifier.

**Pull request closed without merging**
