### PR TITLE
Fish now will respect user's selected prompt

### PR DESCRIPTION
**Pull request by behrangsa**
Fixes IDEA-173259.

See: 
* https://youtrack.jetbrains.com/issue/IDEA-173259
* https://stackoverflow.com/questions/46609023/intellijs-embedded-terminal-does-not-load-fish-functions

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by behrangsa** [comment]
Just signed it.

**Comment by tumasgiu** [comment]
This won't work if one happens to use functions in its `~/.config/fish/config.fish`.
It works as expected if the block sourcing the functions is placed before the one loading the 
`~/.config/fish/config.fish`

**Comment by behrangsa** [comment]
@tumasgiu Thanks for catching this issue. I updated the PR to address it.

**Comment by nazar-pc** [comment]
Just applied this patch locally and it works fine. Hope to see this merged before next release.

**Comment by nazar-pc** [comment]
@traff, what prevents this from being merged? I'm a bit tired to manually patch files after each update.

**Comment by behrangsa** [comment]
Judging by his activity log, it is possible that @traff (the assignee) is on vacation.

**Comment by behrangsa** [comment]
@Elizaveta239 @bulenkov @vladsoroka any progress on this guys?

**Comment by zaypen** [comment]
Hi @behrangsa 
Can we take care of `~/.config/fish/conf.d/` as well, which is also a important part of configurations of fish,  I think
https://fishshell.com/docs/current/index.html#initialization

**Comment by traff** [comment]
Merged

**Pull request closed without merging**
