### PR TITLE
IDEA-123453 Maven failsafe environment variables

### PR DESCRIPTION
**Pull request by diorcety**
All in the title

### CODE REVIEW

**Comment by diorcety** [comment]
Hi,
Have you plan to add this feature?
Regards,

**Comment by rbellamy** [comment]
@klikh - what's the status of this PR? It's almost two years old, and I'm still having issues with the problem this resolves.

**Comment by cinlloc** [comment]
Hi, I would like to know status of this PR also.

**Comment by vladsoroka** [comment]
merged, thanks for the contribution!
ps., sorry for the delay

**Pull request closed without merging**
