### PR TITLE
Fix L&F change in ProjectView panel

### PR DESCRIPTION
**Pull request by dahlstrom-g**
Switching L&F didn't use to update the ProjectView panes except the one
that was displayed at the time.

http://b.android.com/208136

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@SergeyMalenkov? @xtmq?

**Comment by bulenkov** [comment]
Thanks! Merged 210f54d14e0b99fd0fc4f08b66925b2379250198

**Comment by dahlstrom-g** [comment]
@gregsh Do you prefer to revert commit 210f54d then?
@jgaillard85 What's your understanding of the situation?

**Comment by bulenkov** [comment]
@gregsh Thanks! I started Android Studio from sources from master and can't reproduce the problem with or without the fix. So, we probably need to revert it. 

P.S.
The only thing I noticed is wrong foreground for Design Editor
image

@dahlstrom-g Please, use JBColor with function for such cases 
image

**Pull request closed without merging**
