### PR TITLE
Fix for a null-pointer exception while decompiling

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by jsight** [comment]
I have not and was not aware that a CLA was necessary for something like this. Perhaps this can be treated as a bug report and recoded instead?

**Comment by trespasserw** [comment]
Jesse, a CLA is needed for applying the patch under your name.
Sure I can commit the fix myself if you like.

**Comment by jsight** [comment]
@trespasserw - Ok, that is fine, I don't care about the attribution. :)

**Comment by trespasserw** [comment]
Commited as 6fdcf291aa34b3d6fc5f3514e613d265448d03bd. Thanks!

**Pull request closed without merging**
