### PR TITLE
Fix IDEA-92793

### PR DESCRIPTION
**Pull request by rosti-il**
To make Git compatible patch use this new check box:
image

### CODE REVIEW

**Comment by ssx** [comment]
@NadyaZabrodina when will this get merged in?

**Comment by dmitriysmirnovjb** [comment]
Thank you for your contribution.

We actually went further and made the git format the default and only supported, as all the VCSs that are officially supported in IntelliJ IDEA 2020.3 can handle it.

**Comment by ssx** [comment]
That's fantastic news! Thank you @dmitriysmirnovjb - how long until this is released in a version?

**Comment by dmitriysmirnovjb** [comment]
It will appear in 2020.3. EAP will appear in a week or two, the release is planned for the end of the year

**Comment by ssx** [comment]
Superb, thanks Dmitriy!

**Pull request closed without merging**
