### PR TITLE
KTIJ-19379 Add names in comment for java call arguments

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-19379

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
Thanks a lot for your contribution.

**Comment by vladimirdolzhenko** [comment]
merged as https://github.com/JetBrains/intellij-community/commit/707fa508847a555312e56a622c3fa44a15e7a0eb

**Comment by vladimirdolzhenko** [comment]
Looks like it could be follow up tasks

- Inlay hints should be turned off when comments were added:
image

- Add some diagnostic on inconsistency between comments and parameter names

WDYT ?

**Comment by t-kameyama** [comment]
> Looks like it could be follow up tasks
> 
> * Inlay hints should be turned off when comments were added:
>   image
> * Add some diagnostic on inconsistency between comments and parameter names
> 
> WDYT ?

I've created https://github.com/JetBrains/intellij-community/pull/1695.

**Pull request closed without merging**
