### PR TITLE
KTIJ-16267 Intention "Convert lambda to reference": NONE_APPLICABLE with overloaded functions

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-16267

### CODE REVIEW

**Comment by nikita-nazarov** [comment]
Hi! The intention is not applicable in this case:
```
fun foo(f: (Int) -> Int) = f(10)

fun main() {
    val random = foo {<caret> java.util.Random().nextInt(it) }
}
```
But it should be

**Comment by t-kameyama** [comment]
Fixed 7c99cee

**Comment by nikita-nazarov** [comment]
This case is processed incorrectly:
```
fun List<Int>.foo() = firstOrNull()

fun main() {
    listOf(1, 2, 3).apply { foo() }
}
```
Results to:
```
fun List<Int>.foo() = firstOrNull()

fun main() {
    listOf(1, 2, 3).apply(List::foo)
}
```
Also, be aware of something like:
```
typealias ListInt = List<Int>

fun ListInt.boo() = firstOrNull()

fun main() {
    listOf(1, 2, 3).apply { boo() }
}
```

**Comment by t-kameyama** [comment]
Added 9949b6e972eacd3edd44c4d1f43a8fa8c5eef580

**Comment by nikita-nazarov** [comment]
Hi! The intention is not applicable in this case:
```
fun <T> PairIntT<T>.boo() = this

typealias PairIntT<T> = Pair<Int, T>

fun main() {
    Pair(1, 1).apply { boo() }
}
```
It is indeed tricky with variadic templates. Be aware of this example:
```
class A<T1, T2, T3>

typealias AIntListT1T2<T1, T2> = A<Int, List<T1>, T2>

fun <T1, T2> AIntListT1T2<T1, T2>.foo() = this

fun main() {
    A<Int, List<Int>, Int>().apply { foo() }
}
```
Should be converted to:
```
A<Int, List<Int>, Int>().apply(AIntListT1T2<Int, Int>::foo)
```

**Comment by t-kameyama** [comment]
Added 2767a2a

**Comment by nikita-nazarov** [comment]
Hi! The intention should not be applicable in this case:
```
fun main() {
    with (listOf(1, 2, 3)) {
        1.apply { this@with.size }
    }
}
```

**Comment by t-kameyama** [comment]
Merged the latest master(2b1f6294).

**Comment by nikita-nazarov** [comment]
Thanks! Can you also please squash your commits, rebase the branch on master and force push it?

**Comment by t-kameyama** [comment]
> Thanks! Can you also please squash your commits, rebase the branch on master and force push it?

Done

**Comment by nikita-nazarov** [comment]
Thanks for your contribution!

**Pull request closed without merging**
