### PR TITLE
Add option for JavaDoc continuation indent.

### PR DESCRIPTION
**Pull request by c2nes**
This fixes https://youtrack.jetbrains.com/issue/IDEA-23188

This change is based on #526 so the first commit can be ignored.

### CODE REVIEW

**Comment by c2nes** [comment]
Just bumping to see if someone could take a look or if there's any problems with this change that I can look into.

**Comment by lepenkinya** [comment]
Hi, Chris!
Thanks for the contribution!
I've checked, made few small corrections and generally everything seems fine to me. Just one thing - please add corresponding tests into JavadocFormatterTest and attach patch here.

**Comment by lepenkinya** [comment]
Or verify if I covered all cases in https://github.com/JetBrains/intellij-community/commit/e1405ba1a4a9c2fa8f38defded9b3c10ba239971

**Comment by c2nes** [comment]
Thanks @lepenkinya. That test looks good to me, apologies for not including one initially.

**Pull request merged**
