### PR TITLE
CodeDocumenationAwareCommenter: Fix copy/paste issues

### PR DESCRIPTION
**Pull request by Turbo87**
This PR fixes two small copy/paste issues in the `CodeDocumenationAwareCommenter` interface

### CODE REVIEW

**Comment by klikh** [comment]
I've merged the pull request, thank you!

**Comment by Turbo87** [comment]
hmm, it doesn't show up in the `master` branch yet?

**Comment by klikh** [comment]
This github repository is a mirror of the [main one](http://git.jetbrains.org/?p=idea/community.git;a=commit;h=07af579d00c82519ccb448d0b03c5af844a879a6) and is updated once per hour.

**Comment by Turbo87** [comment]
@klikh I see, thanks for the clarification

**Pull request closed without merging**
