### PR TITLE
Support fetch for svn bridged repos

### PR DESCRIPTION
**Pull request by albfan**
* Detect svn remotes on parse config
* Parse branches and tags section properties
* Add git svn commands (for read and write)
* Detect svn remotes on fetchAll to do it properly

This is related with [IDEA-26427](https://youtrack.jetbrains.com/issue/IDEA-26427)

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by albfan** [comment]
@klikh Done. I've already sign it. Should I rework the commit with any signature?

**Comment by klikh** [comment]
We've received the CLA, no additional actions are needed, thank you.

**Comment by albfan** [comment]
@kirillk This is just the start. I think this will need more PR to be feature complete:
- git svn dcommit (push like for git-svn)
- git svn clone (I think it needs a UI to configure, but we can start small and support `--stdlayout`)
- git svn tag/branch (will need UI to support --destination)

I expected to discuss implementation on a bugtracker (something like an epic issue "support git-svn" with those subtasks) and implement features one by one doing code review

If I can do anything to speed up the process let me known.

**Comment by klikh** [comment]
Thanks for the contribution. But tbh I'm not sure about the proposed implementation: I'd avoid hardcoding the git-svn stuff right into common logic (like in the GitFetcher) and common structures (like in GitRemote). 

It would be preferable to add support for git-svn via some extension, maybe even via a separate plugin. Of course, git4idea can be extended to provide necessary API. Do you think you could try this approach?

**Comment by albfan** [comment]
Sure! I will try that. Any tips or an initial WIP branch with some boilerplate skeleton would be appreciated. I will close this PR as soon as I have something reworked on top of git4idea

**Comment by klikh** [comment]
Nope, sorry, we didn't start working on git-svn in any way yet. But please don't hesitate should you need an advice about API and something like that.

**Comment by klikh** [comment]
Let's close this request for now then.

**Comment by klikh** [comment]
Btw, in past there was an attempt to do some git-svn: see `GitSvnRemoteBranch`. Not very successful, though, but might be a start. An extension (subclass, maybe) of `GitRemote` might be needed as well.

**Comment by albfan** [comment]
Sounds like a plan! Let me work on it

**Pull request closed without merging**
