### PR TITLE
[IDEA-137253] Fixed renaming class elements when decompiling

### PR DESCRIPTION
**Pull request by ccarpenter04**
Fixes issue IDEA-137253

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by ccarpenter04** [comment]
I'll do that early next week, I won't have access to a printer until monday at the earliest.

**Comment by ccarpenter04** [comment]
I've gone ahead and emailed it to the address that you mentioned.

**Comment by klikh** [comment]
We've received the CLA. Thanks.

**Pull request merged**
