### PR TITLE
IDEA-185872 - Move enum to inner class without static modifier

### PR DESCRIPTION
**Pull request by bedla**
see https://youtrack.jetbrains.com/issue/IDEA-185872 for info

### CODE REVIEW

**Comment by akozlova** [comment]
You did signed the CA, correct?

**Comment by bedla** [comment]
I found that i have send CLA at 14.07.2015 to contribute@jetbrains.com (email with name ivo smid)

**Comment by akozlova** [comment]
Yes, I saw it on our side, just to be sure that it was you. Thanks again. The change looks good, will merge ASAP

**Comment by bedla** [comment]
ahh, ok :) thank you

**Comment by akozlova** [comment]
Merged manually. Thanks

**Pull request closed without merging**
