### PR TITLE
IDEA-132005 fix performance problem in ErrorPaneConfigurable.java

### PR DESCRIPTION
**Pull request by xhumanoid**
Concatenating string without StringBuilder, as result if user have 2000+ problem and total size of result html string will be more 50mb then "Project structure" panel freeze all.

I wait 30 minutes but ui keep freeze, after very simple patch all work fine

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by xhumanoid** [comment]
Yes. I already sent a letter with CLA today.

**Comment by klikh** [comment]
Agreement received, thank you.

**Comment by bulenkov** [comment]
Thanks for the patch. Rewrote and pushed into master. Alarm should work on pooled thread.

**Pull request closed without merging**
