### PR TITLE
Allow InspectionTool description through InspectionToolEntry

### PR DESCRIPTION
**Pull request by i-walker**
Currently, the function loadDescription either loads the description from Resource or returns null if the variable description is not null. 
The intended use-case is when plugin authors want to describe their Inspection with HTML Strings with either 3rd party libs that render to HTML strings or else. 
This option allows maintaining those descriptions in typed values rather than maintaining a bunch of folders and files.

### CODE REVIEW

**Comment by ybedrov** [comment]
Hello,
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by i-walker** [comment]
Thanks :) I've done that

**Comment by i-walker** [comment]
May I ask, if there are any updates, or did I do something wrong with the license agreement?
cc @ybedrov , @rvishnyakov

**Comment by klikh** [comment]
We've received the CLA, that's fine. The developer is assigned and he'll review the fix. Thank you for your patience.

**Comment by akozlova** [comment]
I am so sorry for so late response, missed the notification somehow. 

Looks like that your tool should override `com.intellij.codeInspection.InspectionProfileEntry#getStaticDescription` (and specify `hasStaticDescription = "true"` during tool registration) to get the desired behaviour? Cause `getTool().getDescription()` in essential does exactly this. 

Thank you for your patience

**Comment by i-walker** [comment]
Thanks @akozlova I will review this with the latest version and reopen if, it's not possible. Meanwhile I will close this

**Pull request closed without merging**
