### PR TITLE
KTIJ-19745 False positive "Redundant 'suspend' modifier" with suspend lambda in constructor whish is used inside suspend method

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-19745

### CODE REVIEW

**Comment by nikitabobko** [comment]
Please run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix them all or share your results as a comment.

**Comment by t-kameyama** [comment]
I ran the `Redundant 'suspend' modifier` inspection on the entire intellij-community and found a warning in the android project.

スクリーンショット 2022-01-11 9 48 59

**Comment by t-kameyama** [comment]
It seems that this issue has been resolved by 52a8d75c2cf545bee87579a8856249fc5847921e.
This PR just adds a test for the issue.

**Comment by nikitabobko** [comment]
cc @yanex ^

**Review by abelkov — CHANGES_REQUESTED** [review]
@t-kameyama after regenerating tests I see that a test fails in Fe10BindingLocalInspectionTestGenerated.java, could you please take a look?

**Comment by t-kameyama** [comment]
Added `IGNORE_FE10_BINDING_BY_FIR` to the test.

**Review by abelkov — APPROVED** [review]

**Pull request closed without merging**
