### PR TITLE
Upgrade pip, setuptools and virtualenv

### PR DESCRIPTION
**Pull request by airvzxf**
Removed the old modules as pip, setuptools and virtualenv and added all the new once.

I did a test changing my PyCharm as this steps:

1. I created a new project with virtualenv:
pycharm_01

2. Notice that the versions are old because it take `pip v10` and `setuptools 39`.
pycharm_02

3. I searched in the directory and I found this files here `./helpers`
pycharm_03

4. I replaced the file `./pycharm/lib/pycharm.jar` and changed the versions for `pip`, `setuptools` and `virtualenv`.
pycharm_04

5. I closed the Pycharm and I open it again then create a new project and Bingo the python modules were always updated to this last version.
pycharm_05

Then I checked in the GitHub official project and I notice that the file `.src/com/jetbrains/python/packaging/PyPackageManagerImpl.java` has the references for these modules.

Resources I used:
[PyPI: PIP](https://pypi.org/project/pip/#files)
[PyPI: Setuptools](https://pypi.org/project/setuptools/#files)
[PyPI: Virtualenv](https://pypi.org/project/virtualenv/#files)

NOTE:
The `setuptools` file is a zip file which I extracted and then compressed into a tar.gz

### CODE REVIEW

**Comment by east825** [comment]
Have you signed our contributors agreement already? If you haven't, could you please go to https://www.jetbrains.com/agreements/cla/ and sign it electronically?

**Comment by airvzxf** [comment]
No but I signed a few minutes ago.

**Comment by east825** [comment]
Great! Everything looks good to me (in particular, `pip` and `setuptools` are in sync with their versions bundled with `virtualenv`). Merged. We were actually going to do exactly that for the upcoming 2019.1 release, but you turned out to be slightly ahead :)

Also, we're unlikely to backport these updated packages to 2018.3 as all of them no longer support Python both 2.6 and 3.3 that we're compatible with there.

By the way, no need to reverse-engineer PyCharm -- feel free to directly ask us about the implementation in the issue if you want to submit a pull request

Anyway, thanks for your contribution!

**Comment by east825** [comment]
Integrated as 41dba7b36ca4cbbc8931c6984879dbda99696918.

**Pull request closed without merging**
