### PR TITLE
fix util_methods.copy on NFS

### PR DESCRIPTION
**Pull request by albertz**
Via: https://youtrack.jetbrains.com/issue/PY-37523

### CODE REVIEW

**Comment by east825** [comment]
@albertz Could you please sign the Contributor Agreement at https://www.jetbrains.com/agreements/cla/?

**Comment by albertz** [comment]
@east825 Ok, I did that now.

**Comment by klikh** [comment]
@albertz Sorry, the system didn't receive the CLA for some reason. Could you please try once again? Thanks.

**Comment by albertz** [comment]
I did the CLA again now. Did you get it now?

**Comment by klikh** [comment]
Yep, we've received the CLA. Thank you.

**Comment by east825** [comment]
@albertz Merged! Thank you for the contribution and, again, sorry it took so long.

**Comment by albertz** [comment]
Thanks for merging!

**Pull request closed without merging**
