### PR TITLE
PsiAugmentProvider: add method processDeclarationsInClass

### PR DESCRIPTION
**Pull request by NekoCaffeine**
https://github.com/mplushnikov/lombok-intellij-plugin/issues/21
https://github.com/mplushnikov/lombok-intellij-plugin/pull/968

### CODE REVIEW

**Comment by NekoCaffeine** [comment]
I've submitted the CLA.

**Comment by mplushnikov** [comment]
Thank you @NekoCaffeine

**Comment by NekoCaffeine** [comment]
When this pr is merged, I can port https://github.com/mplushnikov/lombok-intellij-plugin/pull/968 to the built-in version.

**Comment by akozlova** [comment]
@NekoCaffeine Thanks for the PR. As Michail pointed in the initial request I am a bit uncomfortable with the api, I have an alternative suggestion now though I would like to check the idea internally first. Stay tuned.

**Comment by akozlova** [comment]
I've pushed an alternative variant (c2f6df7d9e5c99e5c2cf68c970124b7e2559b75c) to master branch. Anyway, thanks for the contribution!

**Comment by seregamorph** [comment]
@akozlova are you sure about commit id? It is not found

**Comment by mplushnikov** [comment]
It's here: https://github.com/JetBrains/intellij-community/commit/f6ae29748c984faf43c2667a28b1385167b9a4fb

**Comment by seregamorph** [comment]
🤩

**Pull request closed without merging**
