### PR TITLE
Decompiler: Remove 'Integer.valueOf()' boxing of literals

### PR DESCRIPTION
**Pull request by sabi0**
This is a continuation of #552.

Removed `Integer.valueOf()` boxing of literals whose type is detected as `byte` or `short`.

### CODE REVIEW

**Comment by sabi0** [comment]
@gorrus Would you mind checking this?

**Comment by gorrus** [comment]
I'm slightly worried that you do setConstType inside isBoxingCall method, this looks like an invisible side effect. Please find a better place for it.

**Comment by sabi0** [comment]
I removed `setConstType()` from `isBoxingCall()`.
I also fixed another bug: narrowing cast was not applied when target type was `Byte` or `Short`.

On top of that I removed the unboxing calls too. (`intValue()`, etc.)
This should have probably been done in a separate PR, but I couldn't resist.

**Comment by gorrus** [comment]
Thanks, changes merged to master.

**Pull request closed without merging**
