### PR TITLE
[Fernflower] Fixed annotations not being renamed properly and corrected the position of annotations relative to generated comments

### PR DESCRIPTION
**Pull request by ccarpenter04**
I have previously signed a contributor license agreement.

I fixed a bug that caused annotations to not be properly renamed in the generated source code when the annotation was applied to a class, method, or field.

I also changed it so that generated comments about renamed classes, methods, and fields are placed directly on top of the class, method, or field and below the annotations.

### CODE REVIEW

**Comment by trespasserw** [comment]
Could you please add a test case to `plugins/java-decompiler/engine/test/org/jetbrains/java/decompiler/SingleClassesTest.java`?

**Comment by trespasserw** [comment]
While comments between an annotation and a declaration are legal, I consider this as a bad style. Please exclude corresponding changes from the PR.

**Comment by ccarpenter04** [comment]
I'll gladly add a test case for it, but are you entirely sure you want me to move the comments back? I understand why one would say it's bad style in most cases, but at least in the case of the renaming comments it definitely added some confusion. For example, if the code previously looked like this:
@one
public class two {}

after being renamed the comments had it looking like this

// renamed from two
@a
public class b {}

which really confused me at first until I realized it was just awkward placement of the note. Thoughts?

**Comment by trespasserw** [comment]
Doesn't look crystal-clear either:
```java
@a
// renamed from two
public class b {}
```

Probably, a better way would be dropping these comments completely and producing a separate log of all renames when requested.

**Comment by ccarpenter04** [comment]
I agree that it's still not perfectly clear but I feel that it's a step in the right direction. But I do like you're idea of producing a separate log instead because currently those comments are being attached to every single renamed class, field, and method. Would you be okay with the comments being moved where I put them until someone (perhaps even myself) can get around to changing the way the name mapping is output?

**Comment by trespasserw** [comment]
Okay.

**Comment by ccarpenter04** [comment]
I went to write a test case but I realized that I accidentally deleted my fork. Would the best approach be for me to close this pull request, re-fork, reapply these changes, add the test case, and make a new pull request referencing this comment?

**Comment by ccarpenter04** [comment]
"a better way would be dropping these comments completely and producing a separate log of all renames when requested."

What type of format would you like for this? A json file called changed_names.json?

**Comment by trespasserw** [comment]
A new pull request would be easier to merge.

Didn't think much about it, but JSON sounds good enough.

**Comment by trespasserw** [comment]
Ouch, commits from another project.
Can't reopen because PR's repository is gone.

**Pull request closed without merging**
