### PR TITLE
Removed Perl from default extensions

### PR DESCRIPTION
**Pull request by hurricup**
So platform could offer Perl5 plugin from the repo

### CODE REVIEW

**Comment by nicity** [comment]
IMO platform should offer the plugin from repo regardless of presence simple custom file type

**Comment by hurricup** [comment]
Yep, agree, but don't know how to do this :)

**Comment by hurricup** [comment]
Am i getting this right that all file types generated from defaultFileType.xml are AbstractFileType or UserBinaryFileType so i just need to add a checking for it into the PluginAdvertiserEditorNotificationProvider#createNotificationPanel ?

**Comment by nicity** [comment]
Thanks for bringing the issue to our attention. We are working to support this functionality ourselves, it is important part of CE behaviour.

**Comment by hurricup** [comment]
Any news on this feature?

**Pull request closed without merging**
