### PR TITLE
Update reference from jna-utils.jar to jna-platform.jar

### PR DESCRIPTION
**Pull request by dahlstrom-g**
… following commit 30a7f90, which replaced one file with the other.

### CODE REVIEW

**Comment by dahlstrom-g** [comment]
@chashnikov, @trespasserw?

**Comment by chashnikov** [comment]
@dahlstrom-g why do you need this target? As far as I can see it doesn't work even after your fix (looks like jarjar 1.0 is too old and doesn't process modern bytecode properly).

**Comment by dahlstrom-g** [comment]
> @dahlstrom-g why do you need this target?

If you mean the jarjar taskdef, I don't need it to exist in intellij-community. Shall we remove it?

**Comment by chashnikov** [comment]
@dahlstrom-g 
If you need to have such task for Android Studio it's better to have it in intellij-community repository, not in your code, so we can update it when dependencies of 'updater' module changes.

**Comment by dahlstrom-g** [comment]
> If you need to have such task for Android Studio it's better to have it in intellij-community repository, not in your code, so we can update it when dependencies of 'updater' module changes.

We need it for Android Studio, but it hasn't been updated; hence this pull request.

**Comment by dahlstrom-g** [comment]
@chashnikov: Even if this doesn't fix everything, it addresses the issue in the commit message, right? Is there a reason not to do that?

**Comment by chashnikov** [comment]
@dahlstrom-g Ok, I've [applied](https://github.com/JetBrains/intellij-community/commit/35933a089b912835dd31a69f2c73e245d1cca799) your change. However, 'fullupdater' target still fails on my machine with the following exception:
```
BUILD FAILED
.../community/build.xml:58: java.lang.ArrayIndexOutOfBoundsException: 207
	at com.tonicsystems.jarjar.asm.ClassReader.a(Unknown Source)
	at com.tonicsystems.jarjar.asm.ClassReader.readUTF8(Unknown Source)
	at com.tonicsystems.jarjar.asm.ClassReader.accept(Unknown Source)
	at com.tonicsystems.jarjar.asm.ClassReader.accept(Unknown Source)
	at com.tonicsystems.jarjar.ext_util.JarTransformer.process(JarTransformer.java:35)
	at com.tonicsystems.jarjar.ext_util.JarProcessorChain.process(JarProcessorChain.java:31)
	at com.tonicsystems.jarjar.MainProcessor.process(MainProcessor.java:80)
	at com.tonicsystems.jarjar.ext_util.AntJarProcessor.zipFile(AntJarProcessor.java:70)
	at org.apache.tools.ant.taskdefs.Zip.zipFile(Zip.java:1887)
...
```
Updating to jarjar-1.4 fixes this problem, but I don't see why we need jarjar here. Actually the build scripts doesn't use jarjar's main feature, it just unpacks several jars into a single jar.

So if you need to have an 'updater.jar' with all dependencies included to build patches, I can implement this using regular zip tasks and move this code from xml to groovy build scripts and automatically include all dependencies specified in the project configuration, so we won't need to update paths in build.xml next time dependencies of 'updater' module changes. What do you think?

**Comment by dahlstrom-g** [comment]
@chashnikov: A couple of us chatted about this briefly, and getting rid of jarjar there sounds great. Thanks!

**Comment by chashnikov** [comment]
I've [improved](https://github.com/JetBrains/intellij-community/commit/3e08d113e6fab31d66c53ca937372dda79700bba) 'fullupdater' target in build.xml, now it automatically computes all dependencies.

**Pull request closed without merging**
