### PR TITLE
Avoid attaching multiple versions sources

### PR DESCRIPTION
**Pull request by rmfish**
Avoid attaching multiple versions sources and docs with a snapshot dependency
Fix the issue: https://youtrack.jetbrains.com/issue/IDEA-207941

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by rmfish** [comment]
> Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

done :)

**Comment by Barteks2x** [comment]
Is there something that could be done to move this forward? There hasn't been any activity on this for months, with no reason given to not merge it (aside of the merge conflicts that appeared since then). 

This solution appears to be correct and works well for me (even if the code at first looked wrong), and I'm currently using a custom build of intellij 2020.1 with these patches added.

**Comment by vladsoroka** [comment]
@rmfish Thanks for the contribution, however I've found the change is not complete.
E.g. sources of wrong version still can be attached if the sources download is turned off in the build ('idea.module.downloadSources = false').
The root cause of the origin issue is that the current algorithm of the sources/javados discovery from the Gradle cache uses regular Gradle cache structure convention.
E.g.
```
-<user.dir>/.gradle/caches/modules-2/files-2.1/
 -junit/junit/4.12/
  -2973d150c0dc1fefe998f834810d68f278ea58ec/
    junit-4.12.jar
  -941a8be4506c65f0a9001c08812fb7da1e505e21/
    junit-4.12-javadoc.jar
  -a6c32b40bf3d76eca54e3c601e5d1470c86fcdfa/
    junit-4.12-sources.jar
  ...
```

But this "virtual repository" is located under Gradle user home but uses another structure similar to what maven local repo uses:
```
-<user.dir>/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraftforge/forge/1.13.2-25.0.218_mapped_snapshot_20180921-1.13/
 forge-1.13.2-25.0.218_mapped_snapshot_20180921-1.13-recomp.jar
 forge-1.13.2-25.0.218_mapped_snapshot_20180921-1.13-sources.jar
 ...
```

I've added the fix with integration test using the following commit https://github.com/JetBrains/intellij-community/commit/f8be11901d6ff02e99b2fb924631a06ddc440afd

**Pull request closed without merging**
