### PR TITLE
Debugger: do not insert cast to runtime type for non java code fragments

### PR DESCRIPTION
**Pull request by NataliaUkhorskaya**

### CODE REVIEW

**Comment by gorrus** [comment]
This may affect groovy, jsp, etc...

**Comment by NataliaUkhorskaya** [comment]
@gorrus I've just force pushed the pull-request. Now cast should be inserted for groovy, jps and others, but not for Kotlin (and maybe some others where java-like cast won't be parsed)

**Comment by gorrus** [comment]
expression is cached, so if you switch the language it won't add casts as expected.

**Comment by anstarovoyt** [comment]
Thank you for creating this pull request and for your contribution to the IntelliJ platform. We would like to apologize for not acting on it sooner.

The original problem was resolved other way, so I close the PR.

**Pull request closed without merging**
