### PR TITLE
IDEA-171459 fix type cast for int literals used as byte / short

### PR DESCRIPTION
**Pull request by sabi0**
Fixed decompiler to add a type cast for integer values used in `byte` / `short` context.
For example: `Byte.valueOf((byte)123)`

Also removed unnecessary primitive types boxing:
`String.format("%b", new Object[]{Boolean.valueOf(bool)})` =>`String.format("%b", new Object[]{bool})`

### CODE REVIEW

**Comment by ccarpenter04** [comment]
Fixing this issue greatly improves the chances of being able to recompile the output of many java applications that I've worked with at various points in the past. Please consider merging this soon.

**Comment by sabi0** [comment]
Sure. I'll check what can be done about the cast for literals that are within respective value ranges.

It's a bit tricky since the compiler behavior is inconsistent for such values.
Both `byte b = 127;` and `return 127;` are ok. But for example `Byte.valueOf(127)` is an error.

**Comment by gorrus** [comment]
I found a note about this here:
https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.3-500-C

**Comment by gorrus** [comment]
byte[] barr = new byte[]{(byte)0, (byte)0, (byte)0};
same here, casts are not needed

**Comment by sabi0** [comment]
Thanks for the link.

I'll change the code to add the casts for literals only if
a) value is outside respective type range
or
b) value is used as a method / constructor argument

**Comment by sabi0** [comment]
I've realized that literal values will never be "outside respective type range".
E.g. `(byte) 128` will be compiled to `-128`.

**Comment by gorrus** [comment]
merged into master, thanks!

**Comment by sabi0** [comment]
I've just realized that explicit boxing of primitive literals is still present in some cases.
E.g. `Integer.valueOf(1)` in `TestClassLambda.dec`.

Should I create a new PR?

**Comment by gorrus** [comment]
yes, please

**Pull request closed without merging**
