### PR TITLE
hg4idea: Added a compare action to branch popup menu IDEA-187194

### PR DESCRIPTION
**Pull request by idlsoft**
Code for [IDEA-187194](https://youtrack.jetbrains.com/issue/IDEA-187194).
Uses
```bash
hg log -r "reverse(.%branch)"
```
to load changes, otherwise followed git4idea as much as possible

### CODE REVIEW

**Comment by idlsoft** [comment]
@dmitriysmirnovjb You're right, I chose to do it this way so I can easily patch existing IDEA installations before the PR is approved.
This can obviously be done a lot better.

**Comment by idlsoft** [comment]
@dmitriysmirnovjb @AMPivovarov  I moved most of the UI code into `dvcs-impl`, had to play a little catch-up with `GitCompareBranchesDiffPanel` changes.
Hopefully this can be reviewed soon, otherwise it'll need constant re-merging.

**Comment by AMPivovarov** [comment]
Thanks for your contribution!

Sorry for your troubles with conflicts.
I've noticed that it caused merge conflicts (and broke API for some plugins, that you couldn't know), so I thought to resolve them and apply manually.

**Comment by idlsoft** [comment]
@AMPivovarov Thank you for looking into it. I assume it broke things outside the `intellij-community` repo, but why would merge conflicts not be visible on github?

**Comment by AMPivovarov** [comment]
@idlsoft Yes, those were third-party plugins from Plugin Repository.

Merged pull request to 2018.3 branch.

**Pull request closed without merging**
