### PR TITLE
KTIJ-20627 Quick fix adding TODO for "A 'return' expression required"

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-20627

### CODE REVIEW

**Review by nikita-nazarov — COMMENTED** [review]
The code is fine, but the fix should look like:
```
fun test(): String {
    TODO("Provide the return value")
}
```

Instead of:
```
fun test(): String {
    return TODO("Provide the return value")
}
```

Because it better corresponds with the Intellij IDEA policy of default overridings, and adding `return` leads to unreachable code warning.
So all `add return expression` occurrences in code should be renamed to `add todo item`

**Comment by nikita-nazarov** [comment]
Ok then. @t-kameyama Could you please revert your last changes, so the quick fix will add `return TODO`?

**Comment by t-kameyama** [comment]
> Ok then. @t-kameyama Could you please revert your last changes, so the quick fix will add `return TODO`?

done

**Review by ilya-g — APPROVED** [review]
LGTM, let's wait for Nikita's review

**Pull request closed without merging**
