### PR TITLE
[KTIJ-11532] Create member function removes selected code in target Java file

### PR DESCRIPTION
**Pull request by marcin-bukowiecki**
Added selection removal before setting up target editor. 

I wanted to add few test cases but I noticed that all quickfix tests are `kotlin` to `kotlin`. When I try to mix `Create member function` from `kotlin` to `java` my tests are failing (I'm trying to add test data for ` QuickFixMultiModuleTestGenerated`). 

Issue: https://youtrack.jetbrains.com/issue/KTIJ-11532

### CODE REVIEW

**Comment by abelkov** [comment]
@ybedrov please pay attention: Alexey doesn't work on Kotlin anymore. CC @vladimirdolzhenko

**Comment by klunnii** [comment]
@abelkov I'll take a look

**Comment by klunnii** [comment]
To make test data come into effect one needs to update `plugins/kotlin/idea/tests/test/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java` file. It is a generated one. File can be updated by means of `Generate Kotlin Tests` IDEA run configuration. 

After I did this on my local machine (rebased your commits on recent master) I've got `org.jetbrains.kotlin.idea.quickfix.QuickFixMultiFileTestGenerated.CreateFromUsage.CreateFunction.FromKotlin#testMemberFunction`. So far so good. The problem is though that the test passes always successfully whether the fix is applied or not.

**Comment by marcin-bukowiecki** [comment]
So the problem is with testing framework which ignores </selection> in target source file?

**Comment by klunnii** [comment]
You're right. <selection> from `before.Dependency.java` doesn't affect the test. You can check it evaluating `targetEditor.selectionModel.hasSelection()` near the code snippet that you added.
Here is what goes wrong.
1. `EditorTestUtil#extractCaretAndSelectionMarkersImpl` requires that a file has <caret>. Though it's required, it's not enough.
2. Files are opened in editors opened at `CodeInsightTestFixtureImpl#createEditor`. Here the magic `FileEditorManager.getInstance(project)` means that we take implementaition declared in `platform/platform-resources/src/META-INF/PlatformLangComponents.xml`
```
    <component>
      <interface-class>com.intellij.openapi.fileEditor.FileEditorManager</interface-class>
      <implementation-class>com.intellij.openapi.fileEditor.impl.PsiAwareFileEditorManagerImpl</implementation-class>
      <!--suppress PluginXmlValidity -->
      <headless-implementation-class>com.intellij.openapi.fileEditor.impl.TestEditorManagerImpl</headless-implementation-class>
    </component>
```
I.e. `TestEditorManagerImpl` (tests have no UI hence headless). Opening an editor with this manager is supplied with `editor.getSelectionModel().removeSelection()`. Not sure why.
3. Ok, we know that opening an editor clears selection. But we calculate selection afterwords (1)...
4. Selection is cleared twice: first at (2) (<selection> and <caret> are handled)  and then at `CreateCallableFromUsageFixBase#invokeImpl`.

So what I suggest is to remove your test for now. Test infrastructure should be revisited and fixed.

**Comment by klunnii** [comment]
I merged the first commit. Thank you very much!

**Pull request closed without merging**
