### PR TITLE
IDEA-26855 Move system and config directories in Windows under %LOCALAPPDATA%

### PR DESCRIPTION
**Pull request by sprigogin**
The new location of the system and config directories is under %LOCALAPPDATA%\Company Name\Product Name\N.M, where N and M are the major and minor version.

### CODE REVIEW

**Comment by trespasserw** [comment]
Sorry for the later reply.
We've planned the change for IDEA 2020.1, along with a similar one for Linux.

**Comment by trespasserw** [comment]
Done; please take a look at 3bb0a4bfa863c6536ec8ce0cc9fff6c7005b2169.

**Comment by byyxx128** [comment]
Hi, I have tested version 201.3803.71 on Windows. I found there are residual files in %APPDATA%, %LOCALAPPDATA% and %PROGRAMFILES%. The version 193 or former does not have the problem.
I have checked the options to delete these files in uninstaller.
Please check.

**Comment by byyxx128** [comment]
Hi, I have tested version 201.3803.71 on Windows. I found there are residual files in %APPDATA%, %LOCALAPPDATA% and %PROGRAMFILES%. The version 193 or former does not have the problem.
I have checked the options to delete these files in uninstaller.
image
Please check.

**Comment by trespasserw** [comment]
https://youtrack.jetbrains.com/issue/IDEA-231073, should be fixed in the next EAP.

**Pull request closed without merging**
