### PR TITLE
Close All non-project

### PR DESCRIPTION
**Pull request by afdw**
This PR adds action in RMB menu of tabs that closes all non-project files.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please check your inbox: I've just send there the CLA to sign. Thanks.

**Comment by afdw** [comment]
OK, I've just sign it.

**Comment by klikh** [comment]
Received the CLA. Thanks.

**Comment by ignatov** [comment]
@bulenkov, please review.

**Comment by bulenkov** [comment]
Thank you for the contribution. We've recently introduced an action called "Close all Read-Only" which is very very similar to your action. If for some reason the "Close all Read-Only" doesn't work for you, I'd recommend creating a plugin with the "Close All Non-Project" action.
image

**Pull request closed without merging**
