### PR TITLE
KTIJ-17482 Inspection to detect useless Kotlin annotations in Java code

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-17482

### CODE REVIEW

**Comment by nikitabobko** [comment]
Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix all the warnings introduced by the inspection (in separate commit but in this PR) or share your results as a comment.

**Comment by t-kameyama** [comment]
> Please, run the inspection on the entire `intellij-community` project ([how to run the inspection on the entire project](https://www.jetbrains.com/help/idea/running-inspections.html#run-one-inspection)) and either fix all the warnings introduced by the inspection (in separate commit but in this PR) or share your results as a comment.

Found nothing.

**Review by yanex — APPROVED** [review]

**Comment by t-kameyama** [comment]
322a375fc8c9a35a7f16f467cc8e43b47cdcf5b8

**Comment by yanex** [comment]
@t-kameyama Thank you for your contribution! Please note that I added an additional commit with a slight wording change:
https://github.com/JetBrains/intellij-community/commit/713cd233c34b529080a3b66097a5eaf0d519a030

**Pull request closed without merging**
