### PR TITLE
Put path mapping storage behind an interface

### PR DESCRIPTION
**Pull request by salguarnieri**
Use a map to look up path mapping information. This makes the
lookup on the order of the length of the path (in components)
rather than on the order of number of paths that need mapping.

Added support (and a test) for the situation when a mapped path (symlink)
is then remapped by the native file watcher.

### CODE REVIEW

**Comment by salguarnieri** [comment]
I left the original linear list impl in the code so the interface can be examined independently of the map impl. Before the cl is merged, I'd remove the list impl entirely.

**Comment by trespasserw** [comment]
Looks good. But CanonicalPathMapTest does not work :)

**Comment by salguarnieri** [comment]
It passes for me on mac and linux so I'm guessing that it must be failing on my favorite os (windows). I should have a windows laptop waiting for me at the office to debug the test. Is there any abstraction layer in IntelliJ to simulate the windows file system behavior?

**Comment by trespasserw** [comment]
Right, Windows. Um, didn't think it may be platform-dependent, will check it later today.

**Comment by trespasserw** [comment]
There are no such layer - too many small differences. We resorted to having CI agents with all 3 OSes.

**Comment by trespasserw** [comment]
Nothing critical, just file separators. You can go on, I'll make sure the test works before merging.

**Comment by salguarnieri** [comment]
Ah yes, sorry about that.

**Comment by salguarnieri** [comment]
No rush, but I was wondering if you had an estimate on when the merge would happen.

**Comment by trespasserw** [comment]
Oops, sorry :)
I was waiting for you to do final touches (removing a list-based implementation etc).
I'll clean it up and merge it later today.

**Comment by salguarnieri** [comment]
Sorry, I should have clarified sooner. I removed the list based impl and I think I made the test safe for windows.

**Comment by trespasserw** [comment]
Simplified it a bit and pushed upstream. Thanks!

**Pull request closed without merging**
