### PR TITLE
fix IDEA-142594

### PR DESCRIPTION
**Pull request by lancethomps**
add support for ANNOTATION_PARAMETERS_LPAREN_ON_NEXT_LINE and ANNOTATION_PARAMETERS_RPAREN_ON_NEXT_LINE

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by lancethomps** [comment]
@klikh just did

**Comment by ignatov** [comment]
Please update the PR.

**Comment by ignatov** [comment]
@dyadix please review

**Comment by dyadix** [comment]
The code is outdated, JavaCodeStyleBean was removed.

**Pull request closed without merging**
