### PR TITLE
Migrate some usescope to use PsiSearchHelper

### PR DESCRIPTION
**Pull request by brian-mcnamara**

### CODE REVIEW

**Comment by brian-mcnamara** [comment]
@batya239 FYI

**Comment by batya239** [comment]
and a test as you already have done in another PR, please?

**Comment by batya239** [comment]
Probably, it doesn't make sense to use `JavaSourceFilterScope` in JavaFunctionalExpressionSearcher anymore? I think some more proper scope should be used.

**Comment by brian-mcnamara** [comment]
Is a wrapper scope even needed or can we just use the effectiveUseScope?

**Comment by brian-mcnamara** [comment]
@batya239 following up on this, would using effectiveUseScope be fine over the JavaSourceFilterScope?

**Comment by brian-mcnamara** [comment]
Merged in ca35b63d331c5611e70d2b83292f23392ca31882

**Pull request closed without merging**
