### PR TITLE
Decompilation of inverted floating point comparisons (IDEA-196302)

### PR DESCRIPTION
**Pull request by malte0811**
[Bug report](https://youtrack.jetbrains.net/issue/IDEA-196302)
This is a copy of my original PR (as mentioned in the issue), see https://github.com/MinecraftForge/ForgeFlower/pull/11.

`a<b` and `!(a>=b)` have different results if either `a` or `b` is NaN/"Not a number". In that case the first expression will be false, the second will be true. The fix is fairly straightforward, I replace `a<b` with `!(a>=b)` (and the same for other comparisons) when the statement should be true for NaN and prevent simplification of negated floating point comparisons. The test class contains tests for non-inverted and inverted floating point comparisons as well as non-inverted and inverted integer comparisons (the last case can safely be simplified).

### CODE REVIEW

**Comment by LexManos** [comment]
Throwing my support for this, for what it is worth.
I've spent the last several days verifying the changes and how they effect the resulting code.
It all seems to be consistent with the functionality of the pre-decompiled code.

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by malte0811** [comment]
I did sign the CLA.

**Comment by klikh** [comment]
For some reason, I can't find the CLA in our records. Could you please sign or resend it once again?

**Comment by malte0811** [comment]
I signed it again, but I guess I'm doing something wrong if it didn't work the first time. The instructions aren't entirely clear (and I haven't used DocuSign before): Do I need to manually send the document after signing it on the DocuSign website or does DocuSign do that automatically?

**Comment by klikh** [comment]
Now we've received the CLA, everything is fine now. Thanks.

**Comment by ccarpenter04** [comment]
I'd be interested in seeing this edge case resolved.

**Comment by trespasserw** [comment]
Sorry for the late reply.

I just merged the changes. Thanks!

**Pull request closed without merging**
