### PR TITLE
KTIJ-11292 IDE: File with a public class and private top-level members should have a class icon

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KTIJ-11292

スクリーンショット 2021-12-23 11 46 15

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
Could you pls add tests for that ?

**Comment by vladimirdolzhenko** [comment]
I believe [LineMarkersTestGenerated](https://github.com/JetBrains/intellij-community/blob/bd42d1b27ac9f96cca65a5c529a08d3634c67322/plugins/kotlin/idea/tests/test/org/jetbrains/kotlin/idea/codeInsight/LineMarkersTestGenerated.java) could be helpful for test purposes.

**Comment by vladimirdolzhenko** [comment]
Pls check [KotlinIconProviderTest](https://github.com/JetBrains/intellij-community/blob/60b65c8d9cfed08daacb488cd75b7d0f3bbfc2e8/plugins/kotlin/idea/tests/test/org/jetbrains/kotlin/idea/KotlinIconProviderTest.kt) out

**Comment by t-kameyama** [comment]
Added tests:
https://github.com/JetBrains/intellij-community/blob/62e39f1d621546d3ae8d399035e9a6af05427526/plugins/kotlin/idea/tests/test/org/jetbrains/kotlin/idea/KotlinIconProviderTest.kt#L20-L34

**Comment by vladimirdolzhenko** [comment]
Thanks for the amendments. Different icons with internal and private function looks a bit inconsistent to me. I'd like to discuss it with UX.

**Pull request closed without merging**
