### PR TITLE
IDEA-193617 Fix a11y of combo boxes

### PR DESCRIPTION
**Pull request by rpaquay**
This addresses a regression introduced by change 54c98acf.

See comment in code for description of the fix.

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by rpaquay** [comment]
@klikh I am a member of the Android Studio team @ Google.

**Comment by klikh** [comment]
Ah, OK. This info is not visible on your profile page. Thanks for clarification, not CLA is needed in this case.

**Comment by rpaquay** [comment]
Oh, I didn't realize this info was private. I just made it public. Also, I have contributed many a11y fixes in the past couple of years, feel free to contact @forantar, he helped me merge a few dozens of them already.

**Comment by klikh** [comment]
@rpaquay Yep, everything is fine with the legal part now, thanks.

I've forwarded the pull request for responsible developers, they'll review it soon.

**Comment by forantar** [comment]
Hi Renaud,
Thank you for the fix, your contribution to a11y support is very welcome!

**Pull request merged**
