### PR TITLE
Add Protected Hooks to PositionManagerImpl

### PR DESCRIPTION
**Pull request by alonalbert**
Allows AndroidPositionManager to support static methods in interfaces prior to API 24.

See https://youtrack.jetbrains.com/issue/IDEA-321559/Feature-Request-Add-Protected-Hooks-to-PositionManagerImpl

### CODE REVIEW

**Comment by gorrus** [comment]
Have you seen `com.intellij.debugger.NameMapper`? Maybe it is enough?

**Comment by alonalbert** [comment]
Have not seen it. Will try.

**Comment by alonalbert** [comment]
I don't think `NameMapper` solves our issues. Sent you a message on Slack.

**Comment by alonalbert** [comment]
Abandoning this approach. Will update another PR

**Pull request closed without merging**
