### PR TITLE
avoid duplicate String instances of JpsElementChildRoleBase.myDebugName

### PR DESCRIPTION
**Pull request by ryenus**
I was playing with MAT on IDEA and found 2500+ instance of this class (subclasses included).
and there're 600+ instance of String "collection of library root".

So intern() should make sense here.

Null check is not performed as it seems not necessary :-)

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by ryenus** [comment]
@klikh, signed and sent, cheers.

**Comment by klikh** [comment]
We didn't receive it yet. Could you please resend it once again?

**Comment by ryenus** [comment]
@klikh, just resent to contribute@jetbrains.com, could you please check?

**Comment by klikh** [comment]
The CLA was received. Thanks.

**Comment by chashnikov** [comment]
I merged your commit to 'master', thank you for the contribution!

I also [implemented](https://github.com/JetBrains/intellij-community/commit/a2284824ffc49e4ee035abca4626d57b004a39cf) caching of JpsLibraryRootRole and JpsSdkReferenceRole instances to save even more memory (all other roles are singletons), this makes interning unnecessary.

**Pull request merged**
