### PR TITLE
Fixed decompilation of annotation values nested in arrays

### PR DESCRIPTION
**Pull request by szarnekow**
see https://youtrack.jetbrains.com/issue/IDEA-141133

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by szarnekow** [comment]
I signed the CLA.

**Comment by klikh** [comment]
The CA was received, thanks.

**Comment by trespasserw** [comment]
Pushed upstream. Thanks!

**Pull request closed without merging**
