### PR TITLE
Fix: createDirectories doesn't handle symbolic links

### PR DESCRIPTION
**Pull request by hlerebours**
Let's handle it to support symbolic links in configuration
See https://youtrack.jetbrains.com/issue/IDEA-164639

### CODE REVIEW

**Comment by develar** [comment]
I will take a look Monday. Thanks for contribution.

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

**Comment by klikh** [comment]
The CLA was received. Thanks.

**Comment by CrazySherman** [comment]
Just a friendly inquiry, are we still merging this PR?

**Comment by jcrben** [comment]
bump - I'm getting errors due to symlinks which break saving settings...
image

**Comment by develar** [comment]
Fixed in 2017.3 Fix in our common `path.kt`, because there are other places where default Java NIO implementation is not suitable.

**Pull request closed without merging**
