### PR TITLE
IDEA-194080 Provide a way to override the insets in DarculaComboBoxUI

### PR DESCRIPTION
**Pull request by dahlstrom-g**
@kkmic?

### CODE REVIEW

**Comment by kkmic** [comment]
What's the purpose of this ?

**Comment by dahlstrom-g** [comment]
> What's the purpose of this ?

Does the explanation here help?
http://youtrack.jetbrains.com/issue/IDEA-194080

Either way @jlauridsen can clarify. I'm just relaying the commit here.

**Comment by dahlstrom-g** [comment]
Wait—I see IDEA-194080 is closed now. Should this PR be abandoned?

**Comment by kkmic** [comment]
If the main purpose was to improve comboboxes in tables then it was fixed by IDEA-194353. 
Also you can shrink the height of a combobox by setting "JComponent.compactHeight" JComponent client property to Boolean.TRUE

**Comment by dahlstrom-g** [comment]
Thanks! As far as I can tell, this is resolved.

**Pull request closed without merging**
