### PR TITLE
Fixes minor typo in JS auto-completion keywords

### PR DESCRIPTION
**Pull request by marcushg**

### CODE REVIEW

**Comment by klikh** [comment]
Have you submitted a contributor license agreement? If not, please download the PDF from http://www.jetbrains.org/display/IJOS/Contributor+Agreement and then print it out, sign (mention you github account name there), scan and email to contribute@jetbrains.com

**Comment by marcushg** [comment]
done

**Comment by klikh** [comment]
Sorry, didn't receive it yet.

**Comment by marcushg** [comment]
hmmm, tried it again from a different mail provider.

**Comment by klikh** [comment]
Received, thanks.

**Pull request merged**
